inmaps/test000.in
Testing solution...passed! Returned:
DDDRDRDRRRRDRDRRUULDLLLULLLULUURDRDRDDRRURLLLULULLDRDRRRLLLUURDLDRURDRDRRRRDDDLLUDLLURDRRRUUULLLLDURRRRDDDLLLLLURUUULLDRRDDLURUULLDRURDLDDRDRRRRUUULLULLDLLUURDRDRRLLULLDRRLDDRDRRRRUUUULLLLDLLUURDRDRLULLDRR
Solution:
###         
# #         
# ###       
#   ##      
#    ##     
##    ######
 ##        #
  ##  @*** #
   ## **** #
    #  *** #
    #      #
    ########
inmaps/test001.in
Testing solution...passed! Returned:
ULLDDDDDLDRRURDDULLDUUUUUUUULLDRURDDDDDDLDRRURDLLLULLDDDRRRUUUUUUUULLLDDRRLLUURRRDDDDDLDRUUUULLDRURDUUULDDRDDUULLLURDRRDDDUUUUULDRDDDDLLLDDDRRRUUURRDLULLLLDDDRRRUULURRLUUUULUURDDDDDDLLLDDDRRRUULURUUUULLDRURDDDDDRRUUDDLLURDLLULLDDDRRRUULURUUULLDRURDDDDRRUDLLURDLLULLDDDRRRUDLLLUUURRDRR
Solution:
 ###### 
##    ##
#      #
#    # #
#    ###
##   #*#
#### #*#
#     *#
# #  @*#
# ## #*#
#    **#
########
inmaps/test002.in
Testing solution...passed! Returned:
RRUUDDLLUUUURRRLLLDDDDRRRRRRRUUULLLULLLLDDDDRRUUUDDDLLUUUURRRLDDDDLLURDRUUURRRLLLDDLLUURRRRLLLULUURRRDRRURDLLLULLLDDRDRRRUDLLLULUURRRDRRLDDLUDLLURRDRULLLLUURDLDRRRLLUURRDRLULLDDRDRRUDLLURDLDDDRRULDLUUDLLUURRR
Solution:
##########
#        #
#  # *** #
#    *#* #
#   @*** #
# # #### #
#     ## #
#        #
##########
inmaps/test003.in
Testing solution...passed! Returned:
UULRUULLLRUUULLDDDDDDUUURRRDLDUURRULDLLLUUURRDDRDLLRUUULLDDDRRRURULDLDLLUUURRDDRDLUUULLLLLLDDRLDRRLULUURRRRDDDDDUUUUURRDDDDRRDDDLLUUDDRRUUULULUUULLLLLLDDRDRRLLULUURRDDLDRUUURRDDDUUURRDDDRDRDDDLLUUURRDLULUDRRUULULULLDDDDUUUURRDRDDLLRRUULDRDLDRDRDDLLUURUULUUULLDDDUUURRDDDLRRDDLURUL
Solution:
###########
#       # #
# # # #   #
#   # #   #
#   ***@  #
#####*#   #
    #*#   #
    #*# # #
    #*#   #
    #######
inmaps/test004.in
Testing solution...passed! Returned:
RRUUUUULULULLLLDLLLUULLLLDDRRRRRRRDRULURRRRURDLDRURDDDDDDDRDLDLURULLLLRRRRUUUUULULULLLLDLLLLLLLUURRDULLDDRRRRRRRDRURURRDRDRDDDDDLLLLLRRDDLLLUULURLDDRDRRRUURRRUUUUULULULLDLLURRRRURDLDRURDDDDDDDRDLDLURULLLLLRRDDLLLULUURRDRRDDLLLUULURDRULLDDDRRRRUURRRUUUUULULULLLDLLLLLLLLDDDDDRRRUUUUDDDDLLLUUUUURRRRRRRDRULURRRRURDLDRURDDDDDDDRDLDLURULLLLLRRDDLLLUULURLDDDRRRRUURRRUUUUULULULLLLDLLLLDDDDDLLLUURRLLDDRRRUUUUDLDLLUUURRRRRRRDRULURRRRURDLDRURDDDDDDDRDLDLURULLLLRRRRUUUUULULULLLLDLLLLDDDDDLLULURRLDDRRUUUUDLDLLUUURRRRRRRURRRRDRDRDDDDDLLLLLRRDDLLLUURRRRRRUUUUULULULLLLDDRULURRRRURDLDRURDDDDDDDRDLDLURULLLL
Solution:
#######    ####  
#     ######  ## 
# # #  #       # 
#          #   # 
# ## ###  ###  # 
# #  # #### ## # 
#    #  ###  # # 
#  # ####*#### # 
#    ## *** ## ##
#######  *@     #
      #  ## #   #
      #     #  ##
      ########## 
inmaps/test005.in
Testing solution...passed! Returned:
DDDRURDLLLLUULLDRURDLLDLLDDRLUURRURRRRDRRURRDRDDLLLLLDLURRRRRRUUUURRDLULLDDRDDLLLUUDDRRRUULUURRDRDDDLLLLDLURRRUULULULLDRRURRDDUULLLLLLLDLLDLLDDRRUUURRRDRRRUURRRDRRDDDLLLLLLLLUURULLLULDDLLDDRRRRLLLLUURRURRRDRRRURURRDRRDDDLLLLLLLDLURRRRRRRRUUULLULD
Solution:
      ###       
 ###### ########
 #             #
##         @   #
#   #*    #* # #
# #*##*##*##*# #
#              #
######     #####
     #######    
inmaps/test006.in
Testing solution...passed! Returned:
UULLULLDDDRDDUULUUURRDRRUUULLLLLLDDRRLLUURRRRRRDDDDDDRDDLUUUDDLLLUULUURLULLUURRRRRRDDDDDDRDLLRUUUUUUULLLLLLDDRRDRRRLLLULLUURRRRRRDDDLLULRDRRDULLLULRRDRRUUULLLDURRRDDDLLLLDDRDDRLUULUURRRRUUULLLDDRDRRDDDRDDLUUUUULLULLDDDRDDLRRRLLUULUUURUULLLDDDDRLUUUURRRDDRDRRDDDRDDLULLLUULULLUUUURRRDDRDRRDDDRDLLLDLUUDRRRUUUULLULUULLLDDRLUURRRDDRDRRDDDDLLLLLRRRRRUUUULLULUULLLDDRRLLDDRRUDLLUUUURRRRRRDDUULLLLLLDDDDRRURLDLLUUUURRRRRRDDDDDDRDLLLRRUUUUUUULLLLLLDDDDRRURRLLDLLUUUURRRDDLDDLLUUUURRRRRRDDDDDDDLLDLULLDRURRRRUUUUUUULLLDDRDRLULUURRRDDDDDDRDLLLLRRRUUUULLULLDRRLLDLLUUUURRRRRRDDDDDDDLLLLRRRRUUUUUUULLLDDDRRLULUURRRDDDDDDRDLLLLRRRUUUULLLLDLLUURRLLUURRRDDLDRRRLULUURRRDDD
Solution:
##########
#       ##
# ## ## ##
#     # ##
# #    @##
#   ###*##
### *## ##
####*##  #
#***     #
##  * #  #
##########
inmaps/test007.in
Testing solution...passed! Returned:
LDDLLURDRRRRRRDDLLLLLUDRRRRRUULLLLLLULUUUURRRRRDDDDUUUULLLLLDDDDRDRRULDDDRRRRRUULLUUUUULLLLLDDDDRLLDRUUUUURRRRRDDDDDRRDDLLLLLUURURLDLDDRRRRRUULLLRRRDDLLLLLUULULLDRUUUUURRRRRDDDDLLLUURDLDDDDRRRRRUUUL
Solution:
 ########  
 #      #  
 # #### #  
 # #  # #  
## #  # ###
#  * * *@ #
#  * * *  #
#### #### #
   #      #
   ########
inmaps/test008.in
Testing solution...passed! Returned:
LLDDDLLLLUUURRDRRLLULLDRRULLDDDRRRRUUULRDDDLLLLUUURUUUUULLDRURDDDDDRLLDDDRRRRUUURRDLUUULLUULLDDDDRRRDRULLLLLDDDRRRRU
Solution:
##########
#   ######
# *   * ##
### # # ##
### #   ##
### ###*##
##       #
## * **  #
## ###@###
##     ###
##########
inmaps/test009.in
Testing solution...passed! Returned:
LLLLLLRRRRDDRRRRUULLLLLLLDLURULRDRRRUURRDULLDDDDRRRRUULLLLLLLULDRDLRURRRRRRRDDLURULLLLLLLULDRRRRRRULDLDDRUDRRULLRUUURDLDDRRULDLLULLLLLLLULDRRRRRRRRDRRULLLLLLULLDLLURDRRURDLLLLULULLDDDDRRRUDLLLUUUURRDRRRDRRRRRRDDLURULLLLLLRRRRRRRUULDDRDLULLLLLLURLLLLULLDDDDRRRUUDDLLLUUUURRDRRRDLULLULLDDDDRRRUUDDLLLUUUURRDRRDRRRRRRRUULDRDLLLLLRRRRRDDLURULLL
Solution:
################ 
#   #######    # 
# #   ***##    ##
# ##  * *@      #
# ## #***##     #
#    ######     #
#################
inmaps/test010.in
Testing solution...passed! Returned:
LDDRUDRRRRRULULLRRDDLLULDLLUULUUURRURDUUULDRDDLLLUUUUURRURDDULLLDDDDDRRRUULUURULDDDRDDLLLDDDRDDRRRURLLDLLURRLLULUUURRRUULDRDLUUUURDLDDDDDDLDDRRULDLURRDRRULLLRRRDRRUL
Solution:
##########
###  #####
# *  #####
# #  #####
# #  #####
# # *#####
# #  #####
# *  #####
# # *#####
# # ######
# * **  ##
##*   *@ #
##       #
##########
inmaps/test011.in
Testing solution...passed! Returned:
RRDDLDRRRURUUUUURURRDDDDDDDDDDDDLLULUUUUUUUUURULLULLDRRRLURRLDDRUDLDDDDDDDDDRDRRUUUUUUUUUUULUDRDDDDDDDDDDDLLULUUUUUUUUUURLDDDDDLDLLUUULLUURDLDRDRDDLUUUDDDRRRRDDLLLUULUURDLDRRRLLDDRRRUUUUUUURULULLDRRDDDDDLDLLUULULUURDRDDDLDRRRLLDDRRRUUUUUUUDDDDLDLLUULURDDDRRRDDDDRDRRUUUUUUUUUUUULLLLRRRRDDDDDDDDDDDDLLULUUUUUUUUUULURRLDDRULLLLURDRRDDDDDLDLLDDRRRDDRDRRUUUUUUUUUUULRDDDDDDDDDDDLLULUUUULLLUUULLUURDLDRURDDDLDRRRLLDDRRRUUUUUUU
Solution:
      #### 
  ##### *##
  #  * ** #
###   **  #
#  ###@ # #
#   ## ## #
#   ## ## #
##  ## ## #
 #  #  ## #
 #     ## #
 ## ## ## #
  #    ## #
  #### ## #
     #  # #
     #    #
     ######
inmaps/test012.in
Testing solution...passed! Returned:
UUUULLLLLUURUULLDRURDLDRLULLDDDLDDRRULDLUURURRURDLDRLULLL
Solution:
############
####   #####
###    #####
### #  *####
#*@    #####
#   #  *   #
#    ##### #
#    ##### #
########## #
########## #
############
inmaps/test013.in
Testing solution...passed! Returned:
RDDDRDDDDRLDDRRUUUUUUUUDLDLLUUURRRLLLDDDRDDLLLLLDRLDDRDDRRUUULULURRRDRUUDLLLLUURUUURRDDDRRDRULURRDRULLLDDLDLLLDDRDDDLLUURLDDRRUULURRRRLDDRRUUUUUULURDDDDDDRRDLLLRUULLLLDDDRRUUUUUUDLLLLUURUUURRDDDRRDRUU
Solution:
  ##########
###    #   #
# #      * #
#   # ##*#*#
# # # # @* #
#   #      #
#  ###   ###
#      # #  
#   #    #  
# #      ###
#    # #   #
#  # #     #
##     #####
 #######    
inmaps/test014.in
Testing solution...passed! Returned:
DLLUUULLULLDRRRLUURLUURLDDDDRRDDDRRULDLURRDRRUUURRURRDLLLRDDLRUUUULLUUULLDRLULLDLLDDDDDDRRUDDRRULDLURRDRRURRUULLRRDDLLUDDLLURDRULLLLLLUUUUUURRURRRRDDULLULLDLLDDRRLLUURRDUURRDLULDLLDDDDDDRRRRRRRRUUUUUULRDDDDDDLLLLLLLLUUUUUURRRRRURD
Solution:
###############
#####     #####
###      @  ###
### #*###*# ###
#    **#**  ###
#   #*###*#   #
#    **#**    #
### #*###*# ###
###         ###
#####     #####
###############
inmaps/test015.in
Testing solution...passed! Returned:
LLLULURURRDDLDDRRULUUULDRDDDLLURDRRURURLLRRUULDRDDLLURDRULUURRRDRDDLULLLUURDURRDRDLUULLLDDDLDLLURURLDDRULLLULURURRDLULDLDLDLLURR
Solution:
    ########## 
   ##   #    ##
####    #  #  #
#  @********  #
#   #      #  #
#####    ######
    ######     
inmaps/test016.in
Testing solution...passed! Returned:
DRDDLULLUURDLDRRRRRDRUUUDDLLLLLURRLLULUURDDLDRRLUURRRLLLDDRDRRRRUUUURULLDRDDDDLLLLULUUULUURDLDDRRRRRLLLLDDRDRRRRUUULUURRDLDLLLLLLUURDLDRRRRLLLDDRULURRULDLLUURDLDRRULUURDDDDDLDRRRRDRUUUUURUL
Solution:
#####     
#   ######
#   #**@ #
#    #*  #
#   *** ##
#   ### # 
#   **# # 
#       # 
###     # 
######### 
inmaps/test017.in
Testing solution...passed! Returned:
UULUUUURURRRRRRRRRDDLLDLLULLLRRRDRRULRRRDDDDLLLLLLLLLULDDRRURRURRRRRRUUULLLLDRRURRDDDDDDLLLUDRRRUULLLLLLLLDLLUURDDUULUUUURURRRRRRRRRDDDDDLLLLLLUUURRRRRLDLLULLDDDDLLDLLUUUUUURURRRRRRRRRDDDDDRDLLLLLLLLLDLLUURDLDRURDULULUURURRRRRRRRLDLLULLDDDDLLDLLUUUUUUURRRRRRRRRRDDDDDRDLLLLLLLLLDLLUURDULUUUUURDLDDDDRDRRUURUULLLULDDDURURRRDDLDDLLLDRURRUURUULLLDLDDD
Solution:
##############
#            #
#  ######## ##
#            #
#  ## #   #  #
# ##  ##### ##
#  #         #
#@           #
#* *#### ## ##
#***#  #    # 
#####  ###### 
inmaps/test018.in
Testing solution...passed! Returned:
LLLLUULUURRLLUURRLLDDRRUDLLDDRRLLUURRURRUULDLDDLLDDRRUDLLUUUUURRDRRDLULULLDDDDDRRURULDDLLUUUUURRDRDULULLDRRLLDDDDRRUUURRUULDLDDDDLDDRUUUDLLUUUUURRLLDDDDDRRURRDLULDLLUUUUURRDDDUUULLDDDRLUUURRDRRDLDUULULLDRRLLDDRRURRUULDLDDLLUUURRLUURDDDULLDDDDDRRUDLDDRUULLUUUUURRDRRULDLULUURDLDLDRRLUURD
Solution:
 ####   
 #  #   
##  ### 
#  @  # 
#  ** # 
# #** # 
#  **## 
# #** # 
#     # 
##  ####
 #     #
 #######
inmaps/test019.in
Testing solution...passed! Returned:
LLRDDLLLUUUUURRRDDDUUULLDURRRRRDDLLRRUULLLDLDURURRRDDLLDLURRRUULLDLULLLDDDDDRRRRUDLLLLUUUUURRRDDDDRDLUUUURURRDDLLULDDDRULUURURRDDLLULDRRRUULLLLLLDDDDDDDRRRRULDLLLUUUUUUURRRDDRDDLDLRURUULDUUULLLDDRRLLUURDURRDLRRDDLDURUULDDRDDLRUULULUULLDDDDDDDRRRRUUDDLLLLUUUUUUURRDDRDDURURRUULLLLLLDDDDDDDRRRRUUUULUURURRDDLLULDD
Solution:
#########
#       #
# *   # #
# *     #
# **@ ###
# ##* #  
# *** #  
# *** #  
#     #  
#######  
inmaps/test020.in
Testing solution...passed! Returned:
ULULLLDDRDDDDDRDLRRRUUUULLDDDDRRULLLUULURRLUURDDDDLDDRRULUUUUULLUURRDDDDLDDRDRRUUULLULDRDDUULDLDRLUURRRRDDDLDLLURRLLULUURRDDLDRUUULDDUURUUURRDLULDDDDD
Solution:
###### 
#    ##
# #   #
#     #
##  ###
#     #
#   # #
#  @# #
#*****#
#*    #
#######
inmaps/test021.in
Testing solution...passed! Returned:
RRRRRRRLLDDLDLLLLLLUUURRRRRRRLLLLLLULUURDDLDRRRRRRLLLLLDLDDRRRRRRURUULLLLLLDLDDRRRRUUDDLLLLUURURRRRLDDDRRURURRUULDLDRLDLDLLUUURRRLLLLLLDLDDRUULURRRRRRLLLLLUURURRDDDDUUUULLDLDDDDRDRRRRURURUDLDLDLLLLULUURRRRRRUDDRRUURRDDLRUULLDLLURLDDDLDLLUDLLULUURRRRRLLUUULLDLDDDDRDRRRRURURUULDDULLLLLLDDRDRRUUDDLLULUURRRRRR
Solution:
########      
#       #     
#   # # *#####
#  ## ##  *  #
#       @* * #
#  ## ##  *  #
#   # # *#####
#       #     
########      
inmaps/test022.in
Testing solution...passed! Returned:
DDUURUDLDDRULULLLDDRRUDLLUURRDRRDLULUUDLLDDRRUUURUULDDDLLDDRRURUUDDRDLUUURDLDDRRRUULLULDRRRDDLLUDRRUULLULLUURDURDDDRRDDLLUUDDLLUURLLLDDR
Solution:
  #####  
  #   #  
##     ##
# #***# #
#    *  #
# # * # #
# @*    #
# #***###
#########
inmaps/test023.in
Testing solution...passed! Returned:
URURDDDUULLLRDRURDLLULURRLLLDDDUURRDLDLUURRRDDLL
Solution:
#######
#*   *#
#     #
#     #
#*@  *#
#** **#
#######
inmaps/test024.in
Testing solution...passed! Returned:
URRRDDRRURUUUUUUUUUUDDDDDDDDDDDLLLUULLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDDDDDDDDDDDLLULLLLLRRRRRDRRUUUUUUUUUUUUULLLLLLLLLLLLLLLLDDRRDDDDDDDDDDRRRDDRRRUUUUUUUUUURULDDDDDDDDDDLDLLUURRDRUUUUUUUUDDDDDDDDDRULURRRRRLLLLDDLLUULLLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDDDDDDDDDDDLLUUUUUUUUDDDDDDDLLLLLDDRULULLDDLLUULLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDDDDDDDDDDDLLULLLLDLLLDLLURDRURRRURRRRDRRUUUUUUUUUULLLLLLLLLRRRRRRRRRDDDDDDDDDDLLUUUUUUUUUDDDDDDDDLLLLDLLLLULLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDLLLLLRRRDDDDDDDDDLLLLDLLURRRRRLLLDDLLULLULLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDDDDDDDDDDDLLUUUUUUUUDDDDDDDLLLLLLDLLULLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDLLLLLLLLRRRRRRRRDDDDDDDDDDLLUUUUUUUUUDDDDDDDDLLLLLLDLLULLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDLLLLRRDDDDDDDDDLLLLLLDLLURRRRRRRLLLDDLLUULLLLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDDDDDDDDDDDLLUUUUUUUUDDDDDDDLLLLLLLLLLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDLLLLLLRRRRRRDDDDDDDDDDLLUUUUUUUUUDDDDDDDDLLLLLLLLLLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDLLLLL
Solution:
###################
#                 #
# ############### #
#   #### *####### #
###  ##** **@     #
  # #### * #### # #
  # #  ## ##  # # #
  # #   # #   # # #
  # #   # #   # # #
  # #   # #   # # #
  # #   # #   # # #
  # #   # #   # # #
  # ##### ##### # #
  #             # #
  # ##      ###   #
  ###         #####
    ###########    
inmaps/test025.in
Testing solution...passed! Returned:
UURUDLDDRULULUDRDRRULDLDLURRUULUUUUUUDDDDDDRDDLLLUUURLDDDRRRUULUUUUDDDDRDDLUUDDLLURLUURURUULURDDDLDLDDRDRRUULUUUULUURRDULLDDRDDDDRRULULUULUURRDLDDDLDLDDRULDDRRRUUUULUUUULDRDDDRDDLUUUUUDDDDDLLURDRUUUUDDDDLDDRUUUUU
Solution:
  ###  
## * ##
#  *  #
#  *  #
##***##
  #@#  
##   ##
#     #
#     #
#     #
#     #
##   ##
  ###  
inmaps/test026.in
Testing solution...passed! Returned:
RUUDDLLULLULUURRRRRRLDDDURRDLDUULUULLLLLDDRDRRDRRUUDDDRULLLULLDRRULLULUURRRRRDDDDRULURDRULLUULLLLLDDRDDLUURDRRDRRURDLLLUULDLLUUDDRRUL
Solution:
##########
#*      *#
# #### #*#
#*@  #   #
#    #   #
#       ##
######***#
     #####
inmaps/test027.in
Testing solution...passed! Returned:
RDDRRDDDDRRRUULDRDLLLLRUUUULLDDDDLLDDDDLLLLDDDRRURLDLLUUURRRRUURRDDDDLDLUUUUUUDLLLLUURRRRDDDDDDRRUURRRRDDDLLULLLDLUUUUDLLUURRUUUUUUUURRDDRRRRDDDRDLLLLRUUUULLUULLDDDDDDLLLLLUURDLDRRRLLDDRRRRDDDDRRRRDRRULLLLDLLURDRUUUUDDDLLLLDLLURRRRDRRULDLUUULLUURRUUUUUULLLLDDLDDRRRRLLLLUURUURRRRDDDDLLLLLUURDLDRRRRLLLDDRRDDRRU
Solution:
###############
######   ######
###### # ######
##     #     ##
## ### # # # ##
#  ### # # #  #
#  ### # # #  #
#     ***     #
## ###*#*######
##    ***######
#### #@# ######
##     #     ##
## ### # ### ##
##           ##
##   #   #   ##
###############
inmaps/test028.in
Testing solution...passed! Returned:
UUUURULDLUUUDDDRDDLLDDDRDRUUUUUURULDLUUDRRUULLDDDRDDDDDLLURDRUUUUULURDRUUDLLUURRDDDLDDDDDRRULDLUUUUULURDRUUUDDDLDDDDLULURDRUUURULDLURUDDDDDDRRULDLUUUULURDRULURDDLDDDRRULDLUUURUULDUL
Solution:
  ###  
##* *##
#* * *#
#*@  *#
##   ##
 # * # 
### ###
#     #
#     #
#     #
#     #
##   ##
  ###  
inmaps/test029.in
Testing solution...passed! Returned:
LLUURLDDRRUUDDLLDDRRUUDRRRULURRRRRLUUULLLLLLLLDDDDRRDRDDRRRRRRUURUUUDLLUURRDRUDDLDDLDDLLUUUDLLUURRRRLUUULLLLLLLLDDDDRRDRRRRRDDRRUURUUUDLLLDDLLLLDDRULURRRLUURRRRRDDLDDLLUUUDLLUURRRRRUULLDDLLLLDDLLULLUURRDDDRDDLLURRDRUUUDLLUURRRRRRRLUUULLLLLLLLDDRRDRRRDDRRDDRRUURUUUDLLUURRLLULLLLLLDDDDDRDDLLURRDRUUUDLLUURRRRRRRLLLLLULDLDLLUUUURRDDDDDRDDLLURRDRUUUDLLUURRRRRRUUULLLLLLDDRRDRDDRRDDRRUURUUUDDDLDDLLUUUURRLLLULLLDLDLLUUUURRDDDDDRDDLLURRDRUUUDLLUURRRRRRUUULLLLLLDDRRRDDDRRDDRRUURUUDDLDDLLUUUURR
Solution:
##############
#         #**#
# # #####  **#
#       # #* #
# #       @**#
#   #  # ## ##
# #      #   #
#     ## # ###
#            #
##############
inmaps/test030.in
Testing solution...passed! Returned:
LLURLUULURRRRRURDDDDDDDLDRRRURDDDDRDLLLLLLDLURULLLUUULLLDDDRRDRUUUDLDLLUUURRURRDLULLLDDDDRRRRRRDRRRRRUUUULLLUUUUUUULLLLLDDDDLLURDRUUULURRRRRURDDDDDDDLDRRRURDDDDRDLLLLLLDLURULLLUUUULLDLDDDRRRRRURDLDRRRRRDRUUUURULLLDLUUUUUUURULLLLLULDDDDRDRRULDLLLRRRULDLUUULURRRRRURDDDDDDDLDRRRURDDDDRDLLLLLLDLURULLLUUUULLDLDDDRRRRRURDLDRRRRRDRUUUURULLLDLUUUUUUURULLLLLULDDDDLDRUUUURRRRRDDDDDDDRRRDDDDLLLLLLULLUUUULLDRURDDUULLLDDDDRRRRRRDRRRRRUUUULLLUUUUUUULLLLLDDDLLLDRURRUUURRRRRDDDDDDDRRRDDDDLLLLLLULLLLLUUURRRDDLDRRRURDLDRRRRRDRUUUURULLLDLUUUUUUURULLLLLULDDDD
Solution:
###############
####  ##  #####
###        ####
###  ####  ####
#### #### #####
#   @   # #####
#  ***  # #####
######### #####
#     ##  #  ##
#     ##      #
# ## ####  #  #
# #  #  #### ##
#       ####  #
###  #        #
######  ###  ##
###############
inmaps/test031.in
Testing solution...passed! Returned:
RRLLLDLDDRURRRRUUURUULLDRDDLLLLDLDRUURRRRDDLLUDRRUUUULLUULLLDDRDRDRRLDDRRUUURRDDDLRUUULLDDRDRULLULLDDRRLLUULULDDLDDRUUDRRUURRDRRUDLLULLLULULUURRRRDRRDULLLULLLDDRDRDRRRUULLUULLLDDDRRDRDDLLUURRRRDDLDLUUDLLUURRLLDDRRRRUUUURULDDDDDLLUURLDDRRUUUULLUURDLULLLDDRDDDLDRRLUURRRRDDLDLUUDLLUURRLLDDRRRRUUUURULDDDDDLLUURLDDRRUUUUDDLLLULULUURDURRDDRLUULLDLDDRRDRRRDRRDLLLDLUUDLLUURRRLDDRRUULLLULLUURURRDDRRLLUULLDLDDRRDRRRUDLLLLUULUURRRRDRLLULLDLDDRRDRRRUUDDLLLULLUURDDDDLDRRLUURRRRDDLDLUUDLLUURRRLDDRRUUU
Solution:
##########
#     ####
#  #  **##
#  # ***##
#   ##@**#
##     # #
#  # #   #
#        #
#  #  ####
##########
inmaps/test032.in
Testing solution...passed! Returned:
DDLRDDLURUULRDDLURUULLLDDRRLLUURRRUULDRDDDLLLUURRLLDDRRRUUDDLDDRUULLLUURRDDUURRRRDDLLLLRRRRUULLDULLUURRDDLUDLDDRUULLLDRLDR
Solution:
  #####  
  # * #  
### * ###
#       #
#  * *# #
# @* *  #
###* *###
  #   #  
  #####  
inmaps/test033.in
Testing solution...passed! Returned:
LLLLDLLUUURUURRDDRLUULLDDLDDDRRURRRURUULDDDDDUUUULLDUUULLDDLDDDRRURUUUULLDRURDDRRDDDDLDRDRULUUUUULLULLDLDDDRRURRLLDLLUUURURRDRRDDDDUUUULLDURRUULRDDLLULUURDDDRRDDDDLDDRRULDLURUUUUULLULLDLDDDRRURRLLDLLUUURURRDRRDDDDDUUUUULLDURRUULLLDLDLDDDRRURLDLLUUURURRDRRDDDDDRDLUUUUUULLDDRLUURRDDDD
Solution:
  ####   
###  ### 
#      ##
#    #  #
#  #    #
# ## #  #
# #     #
#   ## ##
#####*@*#
    # * #
    #*  #
    #####
inmaps/test034.in
Testing solution...passed! Returned:
LDDDLDRRRULLUUUUURDLDDDDLLLDRRRRLLLLDDRULURRRUUURUDLDDRRRRUUULLLDLLUURDDDULLDDRRRLUUUUURRRDULLLDDRRRURDDDURRDDLLUUULLLLUURDURRDDLLULDDDULLDDRR
Solution:
############
####    ####
###   #  ###
###      ###
##    ##   #
## # ### # #
#   @***   #
#    *** ###
#  #########
#  #########
############
inmaps/test035.in
Testing solution...passed! Returned:
RUULLDLLDDDDDRRRRRRRURULLRDDLLLLUUUURRRURRDLLLLULLLLDDRRRUURULDLUURULLLRRRDDRDDRRULLDLURULDLUURULLRRDDRRUURRDLULDDLDDRRULLDLURULDLUURULDDDRDDDDDRRUUUDRRDDLLLLUUUURURRDLLRDDDDLLUUUURULLLULDDLDDRDDRRRUUULLLULDRRRRDDDRRRRULDLUUUDRRDDLLLLUUUURURRDLLRDDDDLLUUUURULLLULDDDDLDDRUULUURURRRDDLLLULDDRDL
Solution:
#############
##***  #   ##
#####  #   ##
###      ####
###         #
##  ##      #
##     # ####
#*  ## #    #
#*@ ## #    #
##         ##
#############
inmaps/test036.in
Testing solution...passed! Returned:
RRRRRRDRULLLLLLLUURRRDULLLDDRRRRLLURULDDLLDDRRUULDRURRRRDDLURUUURRDLULDDDULLLLRRRRDRULUURRDLDLLLLLDLLURRRRRDRRUUULLDRDUURRDLDLLLLLDDRULURRRLLUULDDRDL
Solution:
###########
# *  #    #
# *  # *  #
# *    * ##
# *@ # * # 
# *  # * # 
########## 
inmaps/test037.in
Testing solution...passed! Returned:
DULUURDDLDRUUURRDLULDDLDDDDDDRUDRRULUDDLLURDRU
Solution:
########
#      #
#      #
##  * ##
 # ** # 
 # ** # 
 # ** # 
 # ** # 
 #  @ # 
 #    # 
 ###### 
inmaps/test038.in
Testing solution...passed! Returned:
LLLLLUDRRRUULUURDRRDDLDLLUUUDDDLLURDRRRURUULLLLLDLDRUURRDDUURRRDDLLRRUULLLLLDDDRRLLUUURRDDRRDDRULULLUURRRDRDLUULLUULDDLLDDRLUURRRRRDDL
Solution:
   ####   
   #  #   
 ###  ### 
##      ##
#  #**#  #
#   **@  #
##  **  ##
 #####  # 
     #### 
inmaps/test039.in
Testing solution...passed! Returned:
RRRRRURRDDLUDDLLDLLLLLLUUUUUURDLDDDDDRULUURRRRRRRDRRUULDLLLLLLLLUURRURRRRDRLULLLLDLLDDRRRRRRRRRDDLLUURDLULLLLLLLDDRRDRRUUDDLLULLUURRRRRRRDRRUULDRDLULDULLLLLLLUURRURRDDUULLDLLDDRRRRRRRDRURUULLRRDDLUDLU
Solution:
########    
#       ### 
#   # #*** #
# *## ##@  #
#          #
# *## ##   #
#   # #*** #
#       ### 
########    
inmaps/test040.in
Testing solution...passed! Returned:
UUDDDDURLLRURLLRURLLRULULLDRURDRDDLUURRURRDLLDLLURDRUDDDLDRDRRULDLULUURDDLLDLLURRURRDLULD
Solution:
  #####  
###*#*###
#  ***  #
#       #
#**   **#
##*   *##
#**   **#
#  @    #
#  ***  #
###*#*###
  #####  
inmaps/test041.in
Testing solution...passed! Returned:
DULDRRDRRULDLDLLURRLLLLLDDRULURRRDRRULUULLLDDRRDRRURULDDLLURLLLUURRDULLDDRRLLLDDRULURUURRDDDLRUUULLDDLDDRURRRRURURRDLDLLLLLLDLURRRURLUURDLDDRRRRUULLLULD
Solution:
 ######    
 #    #####
## #@     #
#*******  #
#        ##
#  ####### 
####       
inmaps/test042.in
Testing solution...passed! Returned:
LRDDLLUUDLLRURRRDLLDLLLLUUURURRRDULLLDLDDDRRULDLURRDRRULLDLLUUDDRRULDLURUDRRURLDLLURLDDRRURUUULLLUURDLDDDRDDLUUUUDDRDRRULRDRRULDLLLLUUUURULDDDDDRRULDLUUUUDDDRRDRRULLLDLUUUDDRRRUULLRDRDLLDLU
Solution:
#####    
#** ###  
##* # #  
##*   #  
#**#  ###
#*@     #
#       #
#       #
#########
inmaps/test043.in
Testing solution...passed! Returned:
RLDLDRRRLLUURDRRLLLDRURRUUULLLUURRDLDLURRDRDDDLLUUURULDRRDLRDDLLUURUL
Solution:
 #####  
 #*  #  
 #*  ## 
 #*@  # 
###   ##
#   *  #
#     *#
#   **##
####### 
inmaps/test044.in
Testing solution...passed! Returned:
RUUDDLLUUDDLLLUULUURRURRRUULDULLLDDRRRLLLUURDRLLDDLDDRDDRRRUURLDDLLLUULUURUURRURRRDLULLDLLDDLDDRDDRRRUURURLDLDDRRUUDDRRRUULLRRDDLLLLLLLLUULUURRULURDDLLDDRDDRRRUULRDDRRRRRUULLLDDLLUULURDDDLLLUURLDDRRRUUUUDDDDRRUULRDDLLUURRRRRDDLLLLLLLLUULUURRURDULUURDDUURRDLULDLDDLLDDRDDRRRUUUDDDLLLUURRLLDDRRRUU
Solution:
############
##         #
##      ## #
##  **** # #
#   *****  #
# ##*****###
#    @     #
## ## # ## #
##         #
############
inmaps/test045.in
Testing solution...passed! Returned:
RRDDDLDDLLUUUDDDRDDLUUUDRRUURUULUUURDDDDULULDULLDRLLLDDRLUURRRDDDDRDDLUUUUUDDRDRRRURRUULLRRDDLLDLLUDRRULRRRUULDRDLLDLLLULUUULLLDDRRLLUURRRRLDDDUUURURRDLLLDDLLLUURRURRDRRUULDRDLULLLDLLDDRRRDRDDLUUULLLUURDLDRR
Solution:
############
######  ####
######  ####
###     ####
#   **  ####
#  #**#*   #
#  @*#**#  #
####  **   #
####     ###
####  ######
####  ######
############
inmaps/test046.in
Testing solution...passed! Returned:
RRRRRRRLLLLLDDDLLURDRULLDLLURLUURRRRRRRRURDLDRRLLLDLDLLUUDLDLLULUURRRRRRRRDRULURRLLLULULLLLDRURDDULLULLDDDRRRRRRRLLLLLLLUURRRURDDULLLLDDRRRRRRLLDDDRRURUUUDLLLLLLLDDRRRDRUUDLLLLUURRRRRRLLLLDULLDDRRRDRUUDLLUURRRLUUULLDLLDDRRDDRRDRRURURRUULDULDDRLULLLDDLLUURRRRRDRULLLLLLLLUURRDULLDDRRRRRRRUR
Solution:
#########     
#       ##    
#     # *#####
# # # ## @* *#
#        * * #
# # # ##  * *#
#     # *#####
#       ##    
#########     
inmaps/test047.in
inmaps/test048.in
Testing solution...passed! Returned:
RRRRRUDLLLLDDDRRUUDDLLUUURRRRRDRUUUUUUUURULLLULDRDLULDRDLLRRURURRDDDDDDDDLLLLLLDDRDRUUDLLUURRRRRDRUUUUUUUURULLLULDRDLRURRDDDDDDDDLLLLUUURRDDUULLDDDRRRDRUUUUUUUURULLLRRDDDDDDDDLLUULRDDRRUUUUUUUULLDLDLLDLLUURDLDRURRRURUULDLDURRDLDLLLDLURRRDLLURRRUULDRDLLDLUDRRURURURRDDDDDDDDLLUULULDDURRDDLLDDLLUURRRRRDRUUUUUUUURULLLULDRDLULDRDLLL
Solution:
    ####   
   ##  ####
####      #
#**#   #  #
#*@   ## ##
#*   ### # 
######## # 
  #    # # 
###    # # 
#  # # # ##
#         #
## # ##   #
 #   ######
 #   #     
 #####     
inmaps/test049.in
Testing solution...passed! Returned:
URDDDRRUULDRDLUURULLDLLUDRRRDDDLLURDRRUULULLLULDRRRULDRRDRDDLLUURRDLDLUDRRUULUULLDLLDURRRLLLURDRRURRDLLLLULDRRRULLDRRRDDLURULLL
Solution:
  ######
  #    #
##**** #
#*     #
#*@    #
#*##   #
#*#    #
###    #
  ######
inmaps/test050.in
Testing solution...passed! Returned:
LDLUUUDDDLURULDDDRDRUURUULRULDRDDLDDDDDDLLUURUUDDLDDLLUUURRDRURUUULLDDUURRDDDLDLDDLLUUURRUUURRDDLRUULLDDRDLUUURDD
Solution:
########
####*  #
####*  #
##* *  #
###  * #
##*    #
###   ##
### @ ##
# * * ##
# # **##
# # # ##
#     ##
########
inmaps/test051.in
Testing solution...passed! Returned:
RRRURUUURRDRDDLLDLDRUURRUULDLRUULLDRLULLDRURRDDDDLLULUDRDLRRRUURRDDLRUULLUULLDDRLLDDRULDLDLLURRR
Solution:
   ####### 
  ##     ##
  # * * * #
  #  * *  #
####  * * #
#   @* *  #
#   ##  * #
##### #  ##
      #### 
      #  ##
      #### 
inmaps/test052.in
Testing solution...passed! Returned:
LLLDDLLUURUULURRDLDDLDDRUUUULURDDDLUUDDDLLURRDRUUUDDDRRURRDLLLDLUUULURRLDDDRRULDLUULUR
Solution:
  ######  
  #****#  
  # @**#  
###  #####
#        #
#        #
###   ####
  #####   
inmaps/test053.in
Testing solution...passed! Returned:
RUUDDLLUUDDRRUULUUUDDDRDDRRRUULLULRDRRDDLLLUULULDRRDDLLLLLUURRRRLLLLDDRRRUDLLLUURRRDDRRRRRUULLULRDRRDDLLLUU
Solution:
###########
#         #
# ###*### #
# #     # #
#  *****  #
###* ** ###
#    *@   #
# ## # ## #
#         #
###########
inmaps/test054.in
Testing solution...passed! Returned:
RRUURULRDRRRUUURULLDRDDLDLLURRDRUURULDDDLLLLDDDRLUUURRRRURRDDDDLDLLUULLDLUUDRRRDDLURULRDDRRURUUUUULLUULLDLLURDRRURRDDLUDDRRDDDDLLDRRUUUUULLLLLLDLLURRRRRDRUURULLLLLRRRRDDRRDDDDLLDLLULLUUULURRRRDRUURULLLRRDDDLLLLDDDRRULDLUUURRRRURRDDDDLLLDLURULLDLURRRDDRRURUUUULLLLLDLLURRRDRRUUURRDDDDDDLLLLLLUUURRURDRULLLDLDDRRRDRRRUUUUULULLURDRDDLURULULLLRRRDDDLLLDLLURRLDDDRRRDRRRUUUULLUUULLDRRDRRUULLLDRDDLDLLURRDRUUUDDDLLULLDDDRRRDRRRUULDRDLLLDLURULLDLUUULURRRRDRUURRUULDLDDRU
Solution:
###########
#  * * *  #
# * * * * #
####### @ #
#         #
#       # #
### ####  #
#      #  #
###       #
   ##     #
    #######
inmaps/test055.in
Testing solution...passed! Returned:
DURRDDLLLLLLLRRRRRUURDRDLLLLLLRRRRUURRUULLDURDLULLLDDRDULLUURRRRDRRDDLLDLLLRULRDRRULLDLURULRDRRRRUULLDURRDDLLLLRRRRULULDRDLLDLLUUDDRRULRRUUULLDLLRRURRDLLULLDLULDRRURRDLLRRRRDDLLULUURRDLDDDLUDRRURUULLULLLLDDUURRDLULDRRURRDLLLRRRDDLURUL
Solution:
############
#          #
# * *@     #
# *#*  #   #
# *#*      #
# ***      #
############
inmaps/test056.in
Testing solution...passed! Returned:
LULUURDLDDRRRRRUUUULLDDDUUURRDDDDLLLLLUUURRLDLDDRRRRRUUUULLDDDUULLDLDDRRRRLUUURURDULULULULLDRDDLDDDDRRRUUULLULDRDLRURRRRDUULULULULDDDLDRRRRLDDDLLUULUURUURRDDDLLULDDRDLRUURRRURD
Solution:
 #####   
 #   ##  
 #    ## 
 ## #  ##
 #  #   #
##     @#
#*  # #*#
#*  # #*#
#*     *#
#########
inmaps/test057.in
inmaps/test058.in
Testing solution...passed! Returned:
LLDLLLLURDRRRUULULLLLUULURRRRRRLLLLLDDDDLLURDRUUULURRRRLLLDDDRRRRDRDDLLLLUULURRLLUUURRRRURRDULLDRDRLULLLLLDDDRDDRDRRRUULULLLDLUUULURRRRRURRDULLDLLLLDDDRRRRDRDDLUDLLURUDLLUULUUURRRRURRDDUULLDRLLLLLDDDRDDRRDRRUULULLLDLUUULURRRRRURRDULLDLLLLDDDRRRRDRDDLLUUDDRULLLUULUUURRRRURRDRDDUULULLDRDRLULLLLLDDDRRURDDULLDDRDRRULLDLUUDRRUULLDLUUULURRRRRURRDRDULULLDRRLLLLLLDDDRRRRDRDLDLUURULLLDLUUULURRRRRRDRLUURD
Solution:
      ##### 
 ######   ##
 #       @*#
 #  #### **#
### #  ##**#
#       ##*#
#    #   ###
## #       #
 ###     ###
   #######  
inmaps/test059.in
Testing solution...passed! Returned:
UURUURRRRUURRUURRLLDDLLLLUULLRRDDRRDDLLLLUULUURDDUURRRRLLLLUURD
Solution:
###################
########  ##     ##
#######* @*# #*# ##
#####    *   *   *#
##### #  # #*# ####
##### #  *     *###
##### ##*### ######
##### ##     *#####
##### ## ##########
##### #  ##########
##### # ###########
##### # ###########
##### #############
##### #############
##### #############
#     #############
###################
inmaps/test060.in
Testing solution...passed! Returned:
UUUURULDDDDDDULLLLDLULURDRUUUUUURULULDRDLULDRRDDDDLLLLDLULURDRUUDDRRRRRLDDRRRRRRRRDRUUUDDLLLLLDDDUUURRRRDRDDDLLLLLLLLDLURRRRUUUURRRRRUURULDDDLLLLUUUUULULDLDRURRDDLUDDDDDDDDLLLLLURDRRRRUUUULLLLUURRRLUURRDRDDLUURULLULDRRRDDDDRRRRUUULRDDDLLLLUUUUUL
Solution:
###################
######  ###########
#####    ##########
#####    #  #######
###*#*# # *@  #####
### ### #     #####
#   ### #*#  #*   #
#            ###  #
##  #   ###  ### ##
#####            ##
######  ### ###  ##
########### #### ##
######  *## #### ##
######           ##
#######  ##########
###################
inmaps/test061.in
Testing solution...passed! Returned:
DRRUUURULDDLLUULLDDRRDDRRUUUULLDDRLDDRRUULLLLDRLLDDRULURURRRRDDLLUDRRUULLUURDURRDLULLLULDDDDRLUUURRRRDDDDLLULLLDDRULUR
Solution:
 ####    
 #  #####
 #      #
 # # *  #
## *** ##
# @* # # 
#  #   # 
#  ##### 
####     
inmaps/test062.in
Testing solution...passed! Returned:
RRULUURDDLLRUULDRRURRDDLRDDLRDDLLLLURDRRRUUUUUULLDLDDDLRUUURURRDDDDLLLRRRUULLULDRRRDDLLUDRRDDLLU
Solution:
########
#      #
##   # #
#** *  #
#  * * #
#** *  #
## *@# #
#      #
########
inmaps/test063.in
Testing solution...passed! Returned:
LUULURRRLLDDDRRUUDDLLUUURUUDDLDDDLLLUURLDDRRRUUURUULLDLLUUURRRRDDDLDDDDRRUULULULRDRDRDDLLUURRDDRRRUULLLDDLLLLLUURRURUULDURRUULLLLDDDRLUUURRRRDDLDDDLLLDDRRRUUUDDDRRUUL
Solution:
###########
#         #
# ### ### #
# #     # #
#  *****  #
###* ***###
#   *@    #
# ## # ## #
#         #
###########
inmaps/test064.in
Testing solution...passed! Returned:
RDDDDDDLLUULUUDDRDDRRUUUUUULLUULLLLLLDDRRRDLDRDRLUUULLLUURRRRRRDDRRDDDDDDLLUUUULLDLURRRDDDDRRUUUUUULLUULLLLLLDDRRRRDULLLLUURRRRRRDDRRDDDDDDLLULLDLLURRURRDDRRUUUUUULLUULLLLLLDDRRDDRDDRDDLLULULUURDDRDDRRUULULRURDUUULLLLUURRRRRRDDRRDDDDDDLLUUUUL
Solution:
###########
#         #
# #####   #
#     #   #
##* * *## #
#  * *@ # #
# *   * # #
#  * *  # #
##* * * # #
 ##   #   #
  #########
inmaps/test065.in
Testing solution...passed! Returned:
LUUUUUURUULLLDDDDDRDRUUUUUDDDDDRRUUUDRRUULLLRRRDLDLURULDDDDLLUUUUDDDLLUURLDDRRUUDDDRRUUULUUDDRDDDLLDDRULUULLUURRRURRDDLURULDLUDRDDDLDLUUUDLLUURRRLDDDRRUUURUL
Solution:
######   
#  **#   
# #**####
# #**@  #
#       #
# # #   #
#   # ###
##    #  
 ##  ##  
  #  #   
  ####   
inmaps/test066.in
Testing solution...passed! Returned:
LRRDDRRDDDDLLUULLUUDLRDRRDDDDLLULRDDDUURRUUUULLDLDDRDDLDDDRRRUUUU
Solution:
#########
##*   ###
###*# ###
### #   #
#*  #*# #
##*   # #
#*  # # #
## #*   #
#*  #*###
##*  @###
#*  # ###
##  # ###
## *# ###
##    ###
#########
inmaps/test067.in
Testing solution...passed! Returned:
RDRDULLDUULLDDRDDDDDUUUUURURRURDLLLULDDDDDRDDLLURRURDDUULLUUURURRDLLULDDDDRDDLLURURDLDRRUULLUUURRDDDUUULLLUULDLDRRURDDDDDRDLUUUUURRDLULDDDUURDRRUULUURRDLLULDDDRRUURRDLLULDRDDLDDLDDRRLLUURDUUURUULDDULLDLURUULLDRURDRDRDDUULULLDDRDDRDDLLRRUULDUUULUURDDDURDDUUURRDLULD
Solution:
###########
#         #
#         #
#         #
# #     # #
# #  @  # #
# ## * ## #
# # * * # #
###* * *###
 #* * * *# 
 ######### 
inmaps/test068.in
Testing solution...passed! Returned:
LUUUUUUUULUULLLLLLLDDRDRRLDDDRRRDUUUUDRRLLDDLLLUUULULUURRRRRRRDDRDRDDLUUDLLLUUDDDDLLLUUURRURDDDDRULURRLDDLLLLUUULULUURRRRRRRDRRDDDDLULLLULLLLULUURDDLDRRRRLLDDDRRDDLDRRRRDRUURULDDLLULDLUUDRRDRRUUUUULLDDLLLLULDRRRRDLDRUUURURRRUULRDDLUUDDLLLDDLLLUUURRURDDDDDDLDRRRDRUUUUUUURUULULLLLLDLULDDLDRRRRLLDDDRRRRUURRUUDDLLLDDLLLUUURRURDDDDDDLDRRRDRUUUUUUUDLLLDDLLLLD
Solution:
############
#          #
#    #*#** #
#  ##  #** #
#      ##  #
# # ##     #
#   ##  #  #
#       #  #
# @*#  #*  #
# *#   *#  #
# #        #
#  ###     #
############
inmaps/test069.in
inmaps/test070.in
Testing solution...passed! Returned:
DDRRDDUULDRDRRULDRDDLUDDLLURLDLLURUUUDDDDRRUUDDLLUUUUUDDLDRDDRRUULRRRUULLDUULLDRLUULUURDDD
Solution:
#####    
#   #    
#   #### 
#   #  ##
###@  * #
  #* *  #
##  * * #
#  * *  #
# * * * #
##     ##
 ####### 
inmaps/test071.in
Testing solution...passed! Returned:
UUDRRRRRUUUUUULLLULLULULLDLLDLDLLURRLURRUULDDLDDDDDDLDRRRDRUUUULURRLDDDDDRRRRUUDDLLLLUUUUURRLLDDDDDRRRRRRRRRUUUURRDLULDDDRDLLLLLDLURRRRRUUUUUULLLULLULULLDLRURRDRDRRDRRRDDDDDDLLLLLUDLLLLULLLUUUUURUUDDLDDDDDRRRDRRRRRRRRRUUUUUULLLULLULULLDLDLLULDDDDDDLDRRRDRUUUULURDDDDLLLUURDLUUUURURRURURRDRDRRDRRRDDDDDDLLLLLLLLLLULUULUUURURRURURRDRDRRDRRRDDDDDDLLLLLLLLLUUUUURLDDDDLLUULUUUUURRUULDDLDDDDDRDDRRDRRRRRRRRRUUUUUULLLULLULULLDLDLLULDDRURRURURRDRDRRDRRRDDDDDDLLLLLLLLLLULULLDRRRDRUUUULURDDDDDRRRRRRRRRUUUUUULLLULLULULLDLDLLLDDDUURURRURRLLDLLDLDDDRDDLLURUUUUUURURDRDLLULDDDDDDLDRRRDRUUUUDDDDRRRRRRRRRUUUUUULLLULLULRDRRDRRRDDDDDDLLLLLLLLLULLLUURDLUUUURURRURURRDRDRRDRRRDDDDDDLLLLLLLLLLUL
Solution:
##################
###  #############
###  #   #########
##     *  ########
#     ###   ######
#   #######    ###
## # ****##### ###
## #  ########   #
##  # ###*####   #
#   # ###*#### ###
# *@  ### ####  ##
####            ##
#########  #######
##################
inmaps/test072.in
Testing solution...passed! Returned:
ULULRDRRURLLULRRLDDLUDRDDLDLLULUURURRDRDDRDLLRDDLULRRDRURRUURUULUDRDDLDDLLLUURDLUUURURRDRDDDLDLLDLUUUUULURDRUDLDDDRRLLULDURUULULLDLDDRDRRLLULUURURRDRDDRDDLUUUUUDDDDDDLULURDRUUUURULLLRRRRRDRDDDLLLDLUUUULURRR
Solution:
  #########  
 ##*******## 
## *    @* ##
#   #   #   #
#  #*# #*#  #
##  #   #  ##
 #*        # 
  #*      #  
   ##   ##   
     ###     
      #      
      #      
inmaps/test073.in
Testing solution...passed! Returned:
UURDDRRULDLLUURUULDDLDDRUDRRURUULULLLUURDURRDRD
Solution:
#######
#     #
#  *  #
# * *@#
#* * *#
# * * #
#  *  #
#     #
#######
inmaps/test074.in
Testing solution...passed! Returned:
RURLUUURRDDDLLUURURDLLDDDLLUUURLDDDDRULURLDDDDLLUUUURLDDDDRRUURURULDLDDDLLUUUUUURLDDDDDDRRUURURURRDDUULLDDULLDDDLLUUUUUURURRDRLULLDLDDDDDDRRUURRUURRDDLLULLDDDLLUURLUUUURURRRRRDDDUUULLDRURDLLLULLDLDDDDDDRRUULLUURRLLDDRRURRDLULDLLUUUURRDDUUURRDLULDLLDDDDRRRURUUDDLDLLLUUUURRRURRDLDDDLDLLLUURRRLLLUURRURRDDDLLLLUURRRURD
Solution:
#########
##      #
#    @  #
# #*#*#*#
#       #
# #* *#*#
#       #
# #*#*#*#
#   #####
#########
inmaps/test075.in
inmaps/test076.in
inmaps/test077.in
inmaps/test078.in
Testing solution...passed! Returned:
ULULUURDDDLDRURDDUURULULDDUUUURDDDDDRRURRRRRRUUUULLLDDDLDRRRRURDDLUUUUULLLDDRRLLUURRRDDDULLLDDRRRURDLLLLUURDLDLLLDLLUUUURURRRRRRRDDDDLLLULDDUUURRRRUULDRDDDLLUURURDDDDUUUULULDDDLDRRLUURRDDLLLLLLLULUURDDD
Solution:
############# 
#           # 
#    # #    # 
#     #     ##
#    ##   #  #
#   @        #
# * * # ###**#
# #*###*# #**#
## *  ### ####
 ######       
inmaps/test079.in
Testing solution...passed! Returned:
UUUUUUUUUUUURRRRRRDRURRDLRDRRDDLLLLDDLDDDDDDRRURULDDLLUUUUUURUURRRRUULLLRRRDDLLDLDLLDDDDDDRRUURULULLUURDURUULLDDRDL
Solution:
##############
########*#####
#          *##
# ##### *  ###
# ######*    #
# ########## #
# #####      #
# ##### *  ###
# #####   ####
# ####*@ *####
# ####* * ####
# ##### *  ###
# ##### *  ###
# ##### #  ###
# #####   ####
##############
inmaps/test080.in
Testing solution...passed! Returned:
DDDDDDRLDDDDDRRRRDRRULLLLLDLUUUUUUDDDDDRRRRRRDRRULLLDLLULLLUUUUURURRDDRDRDRDULULULUULLDLDDDDDRRRDRRURLDLLULLLUUUUULURRDLDDDDDRRRUULDRDLLDLUUUUUUDDDDDLLLUURDLDRRDRRURRRLLLDLLURRRURRDDLURULRDDRRUL
Solution:
##############
#### #########
#### #########
#### #########
#### #########
#### #########
### * * ######
##*   * ######
#### ##  #####
#### ###  ####
#  # #  #  ###
#  # #*  # ###
#       *@ * #
###   #      #
##############
inmaps/test081.in
Testing solution...passed! Returned:
LULLDRURRDDLUDRDDLDLLURRDRUUDDRRULLRRDRURUULDRDLLRUUURUULDRDDLDDLDLLLLULUUDDRDRRUUURUULDRDLULLULLDRDDDRDRRUUUUULDRDDDDLLURDRUUDDRRURUURUULUUULLDRURDRDDDDLDDLDLLUUURUULLDRURDLDDDDRRULDLUUDRRRUURUULDURUULDRDDDDLDLLLUUULURDDDDLLLUUURLURDLDDDRRRRRRURUULDDRDLLRUUURUULDRDDLDDLDLLUUUULRDDDDRRULDLUUDLLLUUUURRLLDDDDRRRRRRUURUULUULLLRRRDDRDDLDDLLLUUDDLLLUUUURRDRDDDRRRUURUULDDDRDLLLDLULLLUUURLDDDRRRRRRUUUUUULLLULLDRURRDRRDDDDDDLLLUDRRRUUUUUULLULLDRRRURDDDDDDRDLLLLLLDLUUUULURR
Solution:
 ##########
##        #
# #       #
# ######  #
#  @***#  #
#   * *#  #
## #***#  #
#  ## ##  #
#         #
##       ##
 ######### 
inmaps/test082.in
Testing solution...passed! Returned:
RUDRRLLULURRUULLLLDDDRRDRULLLDDDRRUUDDLLUUURRDDDRULURLDDLLURRURRLLDLURDDRRRRRUUULURULDDRDDDLLLLLUULLUUUURRRRDDRLUULLLLDDDDRRUURRUURRDLRRDDLURULDDRDDDLLLLLUUUURRRLLLDDDLLUUUUURRRRRRDDLLLLDDRULURRRLLLDDLLURR
Solution:
##########
#        #
# ###**  #
# #    * #
#  @*##* #
#     ** #
#   *##* #
#        #
##########
inmaps/test083.in
Testing solution...passed! Returned:
LLLLLLULDDDDRRUUULURRRDLLDDLLRRDRRUUDDLLLUURDDRRURRLLLDLUUUDLURRURDRRULDLLLDDRUDRRRUULURDDDLLLULURURLDDDRRRUULLRRDDLLUUDLU
Solution:
###########
#* ***** *#
#    @    #
##     # ##
#*       *#
#         #
###########
inmaps/test084.in
Testing solution...passed! Returned:
UULURRRLLDDRLLLDLUUDDDRDLDRRRRRLLLDDLDRRLUUULLDDRDLLRUURRUULUUURRDDUULLDDDRDRRULLLLLDLUUDRRRURLUURRDDRLULDLU
Solution:
###########
###*#    *#
### #  ####
### *   *##
#*# @  ####
# #     *##
#     * ###
#        *#
###   *####
###   #####
#*     *###
###########
inmaps/test085.in
Testing solution...passed! Returned:
ULURRRURDDDDRDDLLURDRUULURRRRRLLLLDDDDDLLLLDDDDLDDRUUUUULURRRLUULURRDRUUDDLLDDLUULURRRDRURUUULULLLDDDLDRRRRDRUDDDLLLRUULLDLDDRUUULURRRR
Solution:
#############
####  #######
#     #######
#  ##  ######
## ##*     *#
#  ##**######
#    @*######
#      ######
#      ######
#      ######
#  ##########
#  ##########
#  ##########
#  ##########
#  ##########
#  ##########
#############
inmaps/test086.in
Testing solution...passed! Returned:
LLULLDRRULLLUUUUULURURRDLULDDDDDDUUUUUURRUULDDLDDDDDDLDRRDRRUUUURURRRRDRRUULULLULULLDLLDLULDDDDDDUUUUUURRUULDDRRRURRDLLLLDLURRRRRRDRRDRDDLLULLLUUDDRRRDRRUULULLULLLLLRRRDDDRDRR
Solution:
##############
###  #########
###* #   #####
## *      ####
# *  ## #   ##
#  #### ###  #
## ##*     # #
## ##  #  @* #
## ## ########
#  ## ########
# * * ########
###   * ######
##############
inmaps/test087.in
Testing solution...passed! Returned:
RUUULULLDDDDDDRRRRRUUUUUULLDDDDLLRRUUUURRDDDDDDLLLLLUURRRUUUURRDDDDLLUUUULULDLDRRURRRDDDDLLUUULLLULLLUULLDDRRRRRLLLLLURDRRRRDRRUULDRDLULLLLLUURDLDRRRRLLDDLURULDDDLLURDRURUULULLDDUULLDDRLUURRRRDRRRRLLLLULLLLDDRDRDRRUUUDDDLLULULUURRDRLULLDDRDRDRRURUURRRDRRDDDRRDDLLLLLUUUDDDRRRRRUULLUUULLULLLDLDDLLURDRURUURRRDRRDDDLLRRRRDDLLLLLUURRRUUULLUURDLLLLDDLLLUDRRRUURRRRRDDDDRRUUUULLLULDLLLDDLLLULLUURRRDRRRRRLLLDDLUDLLULLUURRRDRRRRLLLLUURDLDRRRLLLULDDLDRRDRUUDLLUURRR
Solution:
  #####        
###   # ####   
#     ###  ####
# #   @****   #
#   #  #*** # #
##     #*## # #
 ##   ##*## # #
  ######      #
       # #### #
       #      #
       ########
inmaps/test088.in
Testing solution...passed! Returned:
ULLLULLUUUUURURDDULLLDLDRURDDDDUUULLDLDDRDRRRRRRDRULURRLLDLLULLUUUUURRURRRDDRLUULLLDDRLUURRRDDRRLLUULLLDDRRRLLLULLDDDRRRRUDLLLLUUURRURRRDDLDDLLLLUUURRDDUUURRRDDLDDLLLRUUULLDDDDDUURRRRUURUULLLDLLDLDLDLDDRDRRRRRDRRURRULLDDLLURLLULLUURRRRUULRDDLLLLUUURRDRRRUURRDDLRUULLLLLDDDURRDDLLLRUUULLDDDDDUURRRRUULLULLDLDLDLDDRDRRRRRLULLUURRRRUULLUURRRRRDDLLRRUURRDDLRUULLLLLLLDDDDLLDDRRDRDRRURRUULDDLDLLURURLDLLULLUURRUUUURRRRRRRDDLLRRUULLLLLLLDDDDLLDDRRDRRURRLLDDRULURLDLLULLUURRUUUURRRDDLLRDDLLLLUUURRDDURRDDLLLRUUULLDDDDURRRRUURRLLLLDDLLDDUURRRRUULLULLDLDLDLDDRDRRURRDRRRRULLDLLULLDRRRLULLUURRRRUURUURRRRDDLLRRUULLLLDDLDDLLUUULLDDDDDRRDRDRRUURUDLDDLLURDRULURLDLLULLUUUUURRURRDRDLLRUULLDDDURRDDLLLRUUULLDDDDDUURRRRUULLULLDLDLDLDDRDRRRRRLULLUURRRRUURRLLDDLLUUULLDDDDDRRDRDRRURRUDLLDLLURRLLLULLUURRRRUURUURRRRDDLLLLLLRUULLDDDURRDDLLLRUUULLDDDDDUURRRRUULLULLDLDLDLDDRDRRRRRDRRURLDLLURR
Solution:
  #############
  #           #
###    #  # # #
#    #        #
#    # # ######
#  #     #**#  
# ## ##### *#  
#  #   #  * #  
#        @**#  
#######   ###  
      #####    
inmaps/test089.in
Testing solution...passed! Returned:
UUDDLLRRDDUURRRRDRRULLUULLRRDDDDLLUULLLLLLDLLURRUURRLLDDDDRR
Solution:
     #     #     
    #########    
     #     #     
   ###     ###   
 # # #     # # # 
###### #*# ######
 #     * *     # 
 #   # # # #   # 
 #   *     *   # 
 #   # # # #   # 
 #    @* *     # 
###### #*# ######
 # # #     # # # 
   ###     ###   
     #     #     
    #########    
     #     #     
inmaps/test090.in
Testing solution...passed! Returned:
LLDLDLDDRULDLLURLLUURDULUURDRRRDRDULULULRDRRLLLLLDDRRUDDDRRUULRRUULDRURURRDLLL
Solution:
 ####      
##  #######
# *  ##   #
#  * *@   #
# * *  ####
#  * *  #  
# * * * #  
##     ##  
 #######   
inmaps/test091.in
Testing solution...passed! Returned:
RRDDRRDDLUDDLLURLDLLURUUDDDRRUUDDLLUUUUUDDDDDRRUULRRRUULLDUULLDRLDLDURUUULUURDDD
Solution:
#####    
#   #    
#   #### 
#   #  ##
# *@  * #
 ##* *  #
##  * * #
#  * *  #
# * * * #
##     ##
 ####### 
inmaps/test092.in
Testing solution...passed! Returned:
UUDDRRLLDDUULLLLULLDRRUURRLLDDDDRRUURRRRRRURRDLLUULLRRDDDDLL
Solution:
###############
#######*#######
###   * *   ###
#   # # # #   #
#   *     *   #
### # # # # ###
###   * *@  ###
#######*#######
###############
inmaps/test093.in
Testing solution...passed! Returned:
LLLDLDLDLDDDLDRRRRDRULURDRULURDRULURDRULURDRULURDRULURRRRURDDDDDDDUUULLDLDLDDDRRRRRRUUUUULLDDDDUUUURRDDDDDLLLLDDLLUURDULUUURURURURDDDDUUULLDLDLDDDDDRUULUUURURURRRRDDDDDLLLLLDLLUURDDRRURRRRUUUUULLDDDDUUUURRDDDDDLLLRUUUUUUUULLLLLDLDLDLDLDLDLLLUURURUDLLUURDRDLULDDDLDRRRRDRULURDRULURDRULURDRULURDRULURDRULURRRRURDDDDDDDUUURRDDDDDLLLLLDLLUURDLDRURDULUUURURURURUULLLLLDLDLDLDLDLDLLLUUUUURURDLDDDLDDRRRRRURURURURURURRRDDDDDDDUUUURRDDDDDLLLRUUUUUUUULLLLLDLDLDLDLDLDLLLUURURURUDLLUURDRDLULDRDLULDDDLDRRRRDRULURDRULURDRULURDRULURDRULURDRULURRRRURDDDDDDDUUURRDDDDDLLLLLDLLUURDLDRURRRRRRUUUUULLDDDDUUUURRDDDDDLLLRUUUUUUUULLLLLDLDLDLDLDLDLLLUUUUURRUURDURRDLLULDDURRDLLULDDURRDLLULDDDDLDRRRRDRULURLDLLLUUUURRDLULDDLDDRRRRRRULLDLLLLUURDLDRRRRURURDRULURDRULURDRULURDRULURRRRURDDDDDDDUUURRDDDDDLLLLLRRRRRUUUUULLLLDLDLDDLDDRURRRRRRUUUUULLDDDDUUUURRDDDDDLLLRUUUUUUUULLLDLDLDLDLDLLLDDRULURURRRURURURURRRDDDLLDLDLDDLDDRRLLUURDLDRUUUURURURRDDDDDLLLRRRUUUUULLDLDLDDDLUURURURURURUULLLDLDLDLDLLLDDRULURDRULURDRULURDRULURDRULURRRRURDDDDDDDDUUUURRDDDDDLLLLLLULD
Solution:
#################  
####     ##  #  #  
###     ##      #  
##     ##    ## ###
#     ##    ##  # #
#    ##    ##     #
#   ##    ##  # # #
#  ##    ##  ## # #
#       ##  ### # #
####*  ##   ### # #
   #**##  @       #
   #######****#####
         ##***#    
          #####    
inmaps/test094.in
Testing solution...passed! Returned:
DDDLLLLULUUURRDLULLLDDRRDRDRRRRUUULLLRRRDDDLLURLDLLULULLUURRRRDRRRDDLLDLLURRLLLULLDRULUURRRRDRRRDDRDLLLULLDRURRDRULLLDRRLLLULULLDRRRRRRLLLLULLUURRDURRDLULLLDDRULUR
Solution:
#######    
# @*  #### 
#  *     # 
#  *####*##
#       * #
####    * #
   ########
inmaps/test095.in
inmaps/test096.in
inmaps/test097.in
Testing solution...passed! Returned:
URRRRRRDDLLLUDRRRUULLLDDRULULLLDDLLUURRLLDRURRLLDDRRURUUUURULDDDDDLDLLURURLDDRURUUUUDDDRRDDRRUULLLRDLLRRDRURULLDLLUUURUUULLDDRLUURRDLDDRUDLDDDRRULDLUUUDDDLRUUURULDDDDLDLLUURRRLDDLURURUUUUURDLDDDDDRRULDLUUUUURULDDDDDLDLLURRDRUUUUDRU
Solution:
   #####   
   #*  #   
   #***#   
   #* @#   
   #*  #   
##### #####
#         #
#         #
#    #    #
###########
inmaps/test098.in
Testing solution...passed! Returned:
RRRRLLLLUUURUULURURDLDDDLDDDRRRRDRRULUUULLLRRRDDDDLLLULLUURLDDRRRRLLLLUURDLDRRRLLUUUUULURURRDLULDDDDDURRRRDDDRDLUUUULLLLDLDDRRRRRLLLLLUURDLDRRLUUUUUURRDLULDDDDLDDRRRLLLUURURRRRDDDDLRUUUULLLLDLDDRRRRLLLLUURURRRRDDDLDRLULLDRULLLUURDLDRRRRLLLUUURRRRDDDUUULLLLUURDLDDDDRRRRUUULLLULDDDLDRRRRLLLUUURRDLULDDLDRRR
Solution:
######   
##   #   
#    #   
#    #   
##  #### 
#      # 
#    # # 
#  ### ##
#   @***#
###  ***#
  #######
inmaps/test099.in
Testing solution...passed! Returned:
RRRRUULLUDLLLLLLDDRRRUDRRRRRUUULUULLLLULDRDRRURRDDLDLLLDDRRUDLLUURRLLDDRRRRRUULULULURURDDLLLLULLDDDLDDRRRUURUDLDDLLLUURUUURRDRRLLLRRDDLLULLDRLDDRRRUURUULULLD
Solution:
####     ####
#  #     #  #
# ######### #
###       ###
  #       #  
 ##@*   * ## 
 # * # # * # 
 #  *   *  # 
 # *# # #* # 
 #         # 
 ########### 
  #       #  
  #########  
   #     #   
   #######   
    #   #    
    #####    
     # #     
     ###     
