inmaps/test000.in
Testing solution...We have searched num gamestates: 3214
passed! Returned:
DDDRDRDRRRRRLLLLLULUURDRDULLDRDRRRDDUULLLUURDLDRDRDRRRLLLULUURDRDULLDRDRLDDRRRUUUULLRRDDDDLLLUUULUURDRRRDDDDRRUUUULLDDDDLLLUURRLLDDRRRRRUUUULLDDLLLDDRULURRLLDDRRRRRUUUULLLLDURRRRDDDDLLLLULURURLULDUULLDRURDLDRRDDLUDRDRRRRUUUULLLLLLDRURD
Solution:
###         
# #         
# ###       
#   ##      
#    ##     
##    ######
 ##        #
  ##  @*** #
   ## **** #
    #  *** #
    #      #
    ########
inmaps/test001.in
Testing solution...We have searched num gamestates: 1492
passed! Returned:
ULLDDDDDLDRRURDDULLDUUUUUUUULLDRURDDDDDDLDRRURDLLLULLDDDRRRUUUUUUUULLLDDRRLLUURRRDDDDDLLLDDDRRRUULURRLUUULLDRURDDDUUUUULDRDDLLURUULDLDRDRRDDLLLDDDRRRUULURUULLUURDURDDDDDRRUUDDLLURDLLULLDDDRRRUULURUUULLDRURDDDDRRUDLLLULLDDDRRRUDLLLUUURRDRRLUR
Solution:
 ###### 
##    ##
#      #
#    # #
#    ###
##   #*#
#### #*#
#    @*#
# #   *#
# ## #*#
#    **#
########
inmaps/test002.in
Testing solution...We have searched num gamestates: 652
passed! Returned:
RRUUDDLLUUUURRRLLLDDDDRRRRRRRUUULLLULLLLDDDDRRUUUDDDLLUUUURRDRRRLLLURLLLDRRRRLLLLDDRDRUUULULUURRRDRRLLULLLDDRDRRUDLDDDRRULDLULLUUURRDLLUUURRRRRRDLLULLLLDDRRDRRUDLLURDLLLDDRRUDRRDRRRUUUUULLULLDRRLLULLLDDDDDRRUURRUDLLLULUURRRDRLDUULLLDDRRDDDRRDRRRUUUUUULLLDDDLRUULULLLDDRRRDRULLLDRRUUULLDLDRRR
Solution:
##########
#        #
#  # *** #
#   @*#* #
#    *** #
# # #### #
#     ## #
#        #
##########
inmaps/test003.in
Testing solution...We have searched num gamestates: 645
passed! Returned:
UULRUULLLRUUULLDDDDDDUUULLUUULLDDRLDRRRLLULUURRRRDDDDURRRRULDLLLUUURRDDRDLLRDDUUURRULDDRDLULLLUUURRDDRDLUUULLDDDDDUUUUULLLLDDRDRRLLULUURRDDLDRUUURRDDDUUURRDDDRDDLUUDDRRDDLLUUDDRRUUULUUULULLDDDDUUUURRDRDDLLRRUULDRDLUUULLDDDUUURRDDDLRRDDLURUL
Solution:
###########
#       # #
# # # #   #
#   # #   #
#   ***@  #
#####*#   #
    #*#   #
    #*# # #
    #*#   #
    #######
inmaps/test004.in
Testing solution...We have searched num gamestates: 37774
passed! Returned:
RRUUUUULULULLLLDLLLUULLLLDDRRRRRRRDRULURRRRURDLDRURDDDDDDDRDLDLURULLLLRRRRUUUUULULULLLLDLLLLLLLUURRDULLDDRRRRRRRURRRRDRDRDDDDDLLLLLRRDDLLLUULURRLLDDRDRRRUURRRUUUUULULULLLLDDRULURRRRURDLDRURDDDDDDDRDLDLURULLLLRRRRUUUUULULULLLDLLLLLLLLDDDDDRRRUUUUDDDDLLLUUUUURRRRRRRLLLLDDDDDLLLUURRURDUUURRRRURRRRDRDRDDDDDLLLLLRRDDLLLUURRRRRRUUUUULULULLLLDDRULURRRRURDLDRURDDDDDDDRDLDLURULLLLRRRRUUUUULULULLLDLLLLLDDDLLLDDRRRUUUUDLDLLUUURRRRRRRURRRRDRDRDDDDDLLLDDLLLUULURDDDRRRUULLRRDDLLLUURRRRRRUUUUULULULLLLDDRULURRRRURDLDRURDDDDDDDRDLDLURULLLDDLLLUURUDLLURDDDRRRUULRRRRUUUUULULULLLLDLLLLDDDDDLLULURRURDUUURRRRRRURRDRDRDDDDDLLLLLRRDDLLLUULDDRRRRUURRRUUUUULULULLLDLLLLLDDDLLDDRRUUUUDLDLLUUURRRRRRRDRULURRRRURDLDRURDDDDDDDRDLDLURULLLL
Solution:
#######    ####  
#     ######  ## 
# # #  #       # 
#          #   # 
# ## ###  ###  # 
# #  # #### ## # 
#    #  ###  # # 
#  # ####*#### # 
#    ## *** ## ##
#######  *@     #
      #  ## #   #
      #     #  ##
      ########## 
inmaps/test005.in
Testing solution...We have searched num gamestates: 5321
passed! Returned:
DDDRURDLLLLUULLDRURDLLDLLDDRLUURRURRRRDRRURRDRDDLLLLRRRRUUUURRDLULDRRDDDLLRRUUULLDLULLDLLLDDDRRULRRUULURRURDRRRDDDLLLLDLLLLUDRRRRURRRRUUULLLLLLLLLLLDLLDDRRUUURRRDRRRUURRDRRRDDDLLLLDLLLLUUURULLLULDDLLDDRRRRLLLLUURRURRRDRRRURRURRDRDDDLLLLDLLLLURRDRU
Solution:
      ###       
 ###### ########
 #             #
##             #
#   #*    #* # #
# #*##*##*##*# #
#        @     #
######     #####
     #######    
inmaps/test006.in
Testing solution...We have searched num gamestates: 128601
passed! Returned:
UULLULLDDDRDDUULUUURRDRRUUULLLLLLDDRRLLUURRRRRRDDDDDDRDDLUUUDDLLLLLRRUULUUULLUURRRRRRDDDDDDRDLLRUUUUUUULLLLLLDDRRDRRRLLLULLUURRRRRRDDDLLULRDRRUUULLLDDUULLLDDRRDDDRDDRDLUUULUUULLUURRRRRRDDDDDDRDDLUUDLRUUUULLULLDDDRDDLLDRURRRLLUULUUURUULLLDDDDRLUUUURRRDDRDRRDDDRDDLULLLUULULLUUUURRRDDRDRRDDDRDLLLDLUUDLLDRURRRRUUUULLULUURRRDDUULLLLLLDDRRLLUURRRRRRDDDUUULLLLLLDDDDRRURLDLLUUUURRRRRRDDDDDDRDLLLRRUUUUUUULLLLLLDDDDRRURULDRRULLDDLLUUUURRRDURRRDDDDDDDLLDLULLDRURRRRUUUUUUULLLDDRDRLULUURRRDDDDDDRDLLLLRRRUUUULLULLDRRLLDLLUUUURRRRRRDDDDDDDLLLLRRRRUUUUUUULLLDDDRRLULUURRRDDDDULLLLDLLUURLDDRRURRRRDDDRDLLLRRUUUULLLLDLLUURRLLUURRRDDLDRRLLDLLUUUURRRRRRDDDDDDDLLLRRRUUUUUUULLLDDDRRLULUURRRDDD
Solution:
##########
#       ##
# ## ## ##
#     # ##
# #    @##
#   ###*##
### *## ##
####*##  #
#***     #
##  * #  #
##########
inmaps/test007.in
Testing solution...We have searched num gamestates: 1472
passed! Returned:
LDDLLURDRRRRRRDDLLLLLUDRRRRRUULLLLLLULUUUURRRRRDDDDUUUULLLLLDDDDRDRDDRRRRRUULLUUUUULLLLLDDDDLDRUUUUURRRRRDDDDDRRDDLLLLLUURURLDLDDRRRRRUULLLRRRDDLLLLLUULULLDRUUUUURRRRRDDDDLLLUURDLDDDDRRRRRUUUL
Solution:
 ########  
 #      #  
 # #### #  
 # #  # #  
## #  # ###
#  * * *@ #
#  * * *  #
#### #### #
   #      #
   ########
inmaps/test008.in
Testing solution...We have searched num gamestates: 1229
passed! Returned:
LLLLDRRDDLLLLUURRURRRRDLULDULLDLLURDLDDRRRRUDLLLLUUURUUUUULLDRURDDDDDRRRDRRULUULLUULLDDDDRRRDRULLLLLDDDRRRRU
Solution:
##########
#   ######
# *   * ##
### # # ##
### #   ##
### ###*##
##       #
## * **  #
## ###@###
##     ###
##########
inmaps/test009.in
inmaps/test010.in
Testing solution...We have searched num gamestates: 48815
passed! Returned:
LDDRUDRRRRRULULLRRDDLLULDLLUULUUURRURDUUULDURUULDRDDDDLLLDDDRDDRRRURLLDLLURRLLULUUURRRUULDRDLUURUULDRDDDLDDDLDDRRULRDRRULRDRRULDLLLLUULLUUUUUUUURRDDRDDDLDDDDDLURDRRULLUUUUUURUULUURDDDDLUURULDDDDDRU
Solution:
##########
###  #####
# *  #####
# #  #####
# #  #####
# # *#####
# # @#####
# *  #####
# # *#####
# # ######
# * **  ##
##*   *  #
##       #
##########
inmaps/test011.in
Testing solution...We have searched num gamestates: 21182
passed! Returned:
RRDDLDRRRURUUUUURURRDDDDDDDDDDDDLLULUUUUUUUUURULLULLDRRRLURRLDDRULDDDDDLDLLUUULLUURDLDRDRDDLUUDDRRRRDDLLLUULUURDLDRRRLLDDRRRUUUUUUURULDDDDDLDLLUULUDRDDRRRDDDDRDRRUUUUUUUUUUULUDRDDDDDDDDDDDLLULUUUUUUUUUURLULLDRRDDDDDLDLLUULULUURDRDDDLDRRRLLDDRRRUUUUUUUDDDDLDLLUULURDDDRRRDDDDRDRRUUUUUUUUUUUULLLLRRRRDDDDDDDDDDDDLLULUUUUUUUUUULURRLLDLLURDRRDRUDLDDDDLDLLDDRRRDDRDRRUUUUUUUUUUULRDDDDDDDDDDDLLULUUUULLLUUULLUURDLDRURDDDLDRRRLLDDRRRUUUUUUU
Solution:
      #### 
  ##### *##
  #  * ** #
###   **  #
#  ###@ # #
#   ## ## #
#   ## ## #
##  ## ## #
 #  #  ## #
 #     ## #
 ## ## ## #
  #    ## #
  #### ## #
     #  # #
     #    #
     ######
inmaps/test012.in
Testing solution...We have searched num gamestates: 28
passed! Returned:
UUUULLLLLUURUULLDRURDLDRLULLDDDLDDRRULLDLURUURRRURDLDRLULLLDDLU
Solution:
############
####   #####
###    #####
### #  *####
#*     #####
#@  #  *   #
#    ##### #
#    ##### #
########## #
########## #
############
inmaps/test013.in
Testing solution...We have searched num gamestates: 134
passed! Returned:
RDDDRDDDDRLDDRRUUUUUULURRDRULLLDDLDLLLDDRDDDLLUURLDDRRUULURRRRLDDRRUUUUUUUUDLDLLUUULLDDDLDDLDRLDDRRUULURRRDRUUDLLLLUURUUURRDDDRRDRUULDLLUUURRRLLLDDDRDDDRRDDRRDLLLRUULLLLDDDRRUUUUUUDLLLLUURUUURRDDDRRDRULUR
Solution:
  ##########
###    #   #
# #      * #
#   # ##*#*#
# # # # @* #
#   #      #
#  ###   ###
#      # #  
#   #    #  
# #      ###
#    # #   #
#  # #     #
##     #####
 #######    
inmaps/test014.in
Testing solution...We have searched num gamestates: 1717
passed! Returned:
DLLUUULLULLDRRRLUURLUURLDDDDRRDDDRRULDLURRDRRUUURRURRDLLLRUULLRRDDDDLRUUUULLUUULLDRLULLDLLDDDDDDRRUDDRRULDLURRDRRUDLLULLLLUUUUUURRURRRRDDULLULLDLLDDRRLLUURRDUURRDLULDLLDDDDDDRRRRDRRURRUUUUUULRDDDDDDLLDLLULLLLUUUUUURRRRRURDRRDDDDLLRRDDLLUDDLLURDRU
Solution:
###############
#####     #####
###         ###
### #*###*# ###
#    **#**  ###
#   #*###*#   #
#    **#**    #
### #*###*# ###
###      @  ###
#####     #####
###############
inmaps/test015.in
Testing solution...We have searched num gamestates: 18618
passed! Returned:
LLLULURURRDDUULLDDDRDRRULUULULDRRDDRRULDLDLLURDRRUURRUULDRDDLLURDRULLDDLLURRURRDLUUURRRDRDDLULLLUURDURRDRDLUULLDLDDLDLLURURLDDRULLLULURURRDLULDLDLDLLURR
Solution:
    ########## 
   ##   #    ##
####    #  #  #
#  @********  #
#   #      #  #
#####    ######
    ######     
inmaps/test016.in
Testing solution...We have searched num gamestates: 3849
passed! Returned:
DRDDLULLUURDLDRRRDRULLLURLULUURDRRRRLLLLLDDRRUDLLUURRRLDDLURDDRRRRUUULUURRDLDDDDLLLLUUURRLLDLLURRRLLULUURDDDLDRURDDLDRRRRDRUUUUURULDDDDDLLLLUUURULDLLUURDUURDULLDDDDRRDDRRRRUUUUULRDDDDDLLLLUULLUURDDDLDRRRRRDRUUUUURULDDDDDLLLLUUULUURDLDR
Solution:
#####     
#   ######
#   #**  #
#    #*  #
#  @*** ##
#   ### # 
#   **# # 
#       # 
###     # 
######### 
inmaps/test017.in
Testing solution...We have searched num gamestates: 262
passed! Returned:
UULUUUURURRRRRRRRRDDLLDLLULLLRRRDRRULRRRDDDDLLLLLLLLDLLUURDRRRURRRRRRUUULLLLDRRURRUULLLLLLLLLDLDDDDRDRRUURUURRRRRLDLLULLDDDDLLDDLLUUUUUUURURRRRRRRRRDDDDDRDLLLLLLLLLLULDDURDRURRRRRRRRDDLLLUDRRRUULLLLLLLLDLLUURDLDRURDULULUURURRRRRRRRLDLLULLDDDDLLDLLUUUUUUURRRRRRRRRRDDDDDRDLLLLLLLLUURUULLLLUURDURRRRRRRRRDDLLLLLLLLLULDDRURRRDDDDLLDLLUURDLDRURRUURUULLLLDDDD
Solution:
##############
#            #
#  ######## ##
#            #
#  ## #   #  #
# ##  ##### ##
#  #         #
#@           #
#* *#### ## ##
#***#  #    # 
#####  ###### 
inmaps/test018.in
Testing solution...We have searched num gamestates: 24070
passed! Returned:
LLLLUURLLUUUURRLLDDRRURRUULDLDDLLUUURRDDDLLDDRRUDLLUUUUURRDRRDLULULLDDDDDRRURULDDLLUUUUURRDRDULULLDRRDRRUULDLLLDDDDRRUUDDLLUUUURRRULDLLDDDDRRUUUDDDLLUUUURRDDDDLDDRUUURRDLULDLLUUUURRDDUULLDDRLUURRURRDDLDURUULLDLLURDLDDRRURRUULDLDDLLUUURRLUURDDDULLDDDDDRRUDLDDRUULLUUUUURRDRRULDLULLDRRULUURDD
Solution:
 ####   
 #  #   
##  ### 
#  @  # 
#  ** # 
# #** # 
#  **## 
# #** # 
#     # 
##  ####
 #     #
 #######
inmaps/test019.in
Testing solution...We have searched num gamestates: 2135
passed! Returned:
LLRDDLLLUUUUURRRDDRDLUUURRRDDLLDLDDLLLUUUUURRRDDDULRUURDURRDDLLRRUULLLLLLDDDDDRRRRUULDRDLLDDLLUURLUUUUURRRDDDUURDLDDUURRRUULLLLLLDDDDDDDRRRRULDLLLUUUUUUURRRDDDDDLRUUUUULLLDDRRLLUURRRDDDUUULDRDLRDDRULUURURRDDLLULDDRDDLRUULULUULLDDDDDDDRRRRUUUULUURURRDDLLDLDURUULDD
Solution:
#########
#       #
# *   # #
# *     #
# **@ ###
# ##* #  
# *** #  
# *** #  
#     #  
#######  
inmaps/test020.in
Testing solution...We have searched num gamestates: 323
passed! Returned:
ULULLLDDRDDDDRDDRRUUUULLDDDLULDRRDRRULLLUULURRLUURDDDDUUUULLUURRDDDDDLDDDRRULRRUUULLULDDRDULLDRLUURRRRDDDLDLLURRLLULUURRDDLDRUUULDDUURUUURRDLULDDDDD
Solution:
###### 
#    ##
# #   #
#     #
##  ###
#     #
#   # #
#  @# #
#*****#
#*    #
#######
inmaps/test021.in
Testing solution...We have searched num gamestates: 1214
passed! Returned:
RRRRRRRLLDDLDLLLLLLUUURRRRRRRLLLLLLULUURRRRDDUULLLLDDRDRRRRRLLLLLDLDDRUULURRRRRLUUURRDRDDRDRULLUULULLDDDRRRDULLLLLLDDRDRRUUDDLLULUURRRRRLLUUURRDRDRDULULULLDDDRRRLLLLLLULUURDDLDRRRLLDDRDRRUUUUDRRRURRDDRRUULRDDLLULLDRLUUULULLLLDLDDRRRRRLLDDDLLULUUUURURRRRDRDRDDLUUDLLLLLLUURURRDDUULLDLDDRRRRRR
Solution:
########      
#       #     
#   # # *#####
#  ## ##  *  #
#       @* * #
#  ## ##  *  #
#   # # *#####
#       #     
########      
inmaps/test022.in
Testing solution...We have searched num gamestates: 9979
passed! Returned:
DDUURUDLDDRULULLLDDRRUDLLUURRURUULDDDLLDDRRURRDLUUURDLDDRRRUULLULDRRRDDLLUDLLRRRRUULLULLUURDURDDDRRDDLLUUDDLLUURLLLDDR
Solution:
  #####  
  #   #  
##     ##
# #***# #
#    *  #
# # * # #
# @*    #
# #***###
#########
inmaps/test023.in
Testing solution...We have searched num gamestates: 25
passed! Returned:
URURDDDUULLLULDDDUURRDRLLULDRDURRDRUULULLDDDRR
Solution:
#######
#*   *#
#     #
#     #
#*  @*#
#** **#
#######
inmaps/test024.in
Testing solution...We have searched num gamestates: 8169
passed! Returned:
URRRDDRRURUUUUUUUUUUDDDDDDDDDDDLLLUULLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDDDDDDDDDDDLLULLLLLRRRRRDRRUUUUUUUUUUUUULLLLLLLLLLLLLLLLDDRRDDDDDDDDDDRRRDDRRRUUUUUUUUUURULDDDDDDDDDDDRULUUUUUUUUURURRRRRDDDDDDDDDLLLLLDLUUUUUUUDDDDDDDLDLLUURRRRRRRRLLLLDDLLUULLLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDDDDDDDDDDDLLUUUUUUUUDDDDDDDLLLLLLLDDLURRRDRULULLDDLLUULLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDDDDDDDDDDDLLULLLLRRRRDRRUUUUUUUUUUUUULLLLLLLLLLLLLLLLDDRRDDDDDDDDDDRRRDRRURUUUUUUUDDDDDDDLDLLURLLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDLLLLLLLLLRRRRRRRRRDDDDDDDDDDLLUUUUUUUUUDDDDDDDDLLLLDLLLLULLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDLLLLLLRRRRDDDDDDDDDLLLLDLLURRRRRLLLDDLLULLULLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDDDDDDDDDDDLLUUUUUUUUDDDDDDDLLLLLLDLLURRLLLLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDLLLLLLLLRRRRRRRRDDDDDDDDDDLLUUUUUUUUUDDDDDDDDLLLLDLLULLLLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDLLLLLLRRRRDDDDDDDDDLLLLDLLURRRRRLLLDDLLUULLLLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDDDDDDDDDDDLLUUUUUUUUUDDDDDDDDLLLLLLLLLLLLUUUUUUUUUULLUURRRRRRRRRRRRRRRRDDDLLLLL
Solution:
###################
#                 #
# ############### #
#   #### *####### #
###  ##** **@     #
  # #### * #### # #
  # #  ## ##  # # #
  # #   # #   # # #
  # #   # #   # # #
  # #   # #   # # #
  # #   # #   # # #
  # #   # #   # # #
  # ##### ##### # #
  #             # #
  # ##      ###   #
  ###         #####
    ###########    
inmaps/test025.in
Testing solution...We have searched num gamestates: 11565
passed! Returned:
UURUDLDDLULURUDDRDRULLUURUUUUUUDDDDDDLDDRUUUUUUDDDDDDRRULRUULULUURULDDDRDRDDLDLLUURUUUUDDDDLDDRRUULUUUURUULDULLDRDRDDDDRRULULUULUURRDLULDRDDDRDDLUUUUUDDDDDLLURDRUUUDDDLDDRUULUURUUDDLDDRUUU
Solution:
  ###  
## * ##
#  *  #
#  *  #
##***##
  #@#  
##   ##
#     #
#     #
#     #
#     #
##   ##
  ###  
inmaps/test026.in
Testing solution...We have searched num gamestates: 21666
passed! Returned:
RUUDDLLULLULUURRRRRRLDDDURRDLDUULUULLLLLDDRDRRDRRDRLUUUDDDRULLLULLDRRULLULUURRRRRDDDDRULURDRULLUULLLLLDDRDDLUURDRRDRRURDLLLUULDLLUUDDRRUL
Solution:
##########
#*      *#
# #### #*#
#*@  #   #
#    #   #
#       ##
######***#
     #####
inmaps/test027.in
Testing solution...We have searched num gamestates: 140
passed! Returned:
RDDRRDDDDRRRUULDRDLLLLRUUUULLDDDDRRUUUULLUULLDDDDDDDDDDDDRRUURRRRDDDLLULLLDLUUUUURRDDRRRRDDLLLRDRRUUULLLLUULLDDDDRDRUUUUDDDLLUULLLLDDDRRURRDRRULDLUUUUDLLUURRLLDDLLDDRRRRDRRULDLUUUUDLLUULLUULUURDLDRRRRRUUUULLLLDDDLDRRRLLUUUURRRRUURRDDRRRRDDDRDLLLLRUUUULLUULLDDLLLLDDDDRRR
Solution:
###############
######   ######
###### # ######
##     #     ##
## ### # # # ##
#  ### # # #  #
#  ### # # #  #
#    @***     #
## ###*#*######
##    ***######
#### # # ######
##     #     ##
## ### # ### ##
##           ##
##   #   #   ##
###############
inmaps/test028.in
Testing solution...We have searched num gamestates: 1852
passed! Returned:
UUUURULDLUUUDDRUDDDDLLDDDRDRUUUUUUURULLDDRDDLLDRLDDRRUUUUUULURRDDLDDDDDLUULURDRUUURULDLUDRDDDDDRRULDLUUUUULURDDDDDRRULDLUUUUDDDRRULLUULUURDURUULDLDDRULURDDDRULUURLDDRUDDLDDRDDLLURDRULLLURDRUUUUURUDDDLDDDRRULDLUU
Solution:
  ###  
##* *##
#* * *#
#*   *#
##   ##
 # * # 
###@###
#     #
#     #
#     #
#     #
##   ##
  ###  
inmaps/test029.in
Testing solution...We have searched num gamestates: 195
passed! Returned:
LLUURLDDRRUUDDLLDDRRUUDRRRULURRRRRLUUULLLLLLLLDDDDRRDRDDRRRRRRUURUUUDLLUURRDRUDDLDDLDDLLUUUDLLUURRRRLUUULLLLLLLLDDDDRRDRRRRRDDRRUURUUUDLLLDDLLLLDDRULURRRLUURRRRRDDLDDLLUUUDLLUURRRRRLLUURRLLDDLLLLDDLLULLUURRDDDRDDLLURRDRUUUDLLUURRRRRRRLUUULLLLLLLLDDRRDRRRDDRRDDRRUURUUUULLULLLLLLDDDDDRDDLLURRDRUUUDLLUURRRRRRRLLLLLULDLDLLUUUURRDDDDDRDDLLURRDRUUUDLLUURRRRRRUUULLLLLLDDRRDRDDRRDDRRUURUUUDDDLDDLLUUUURRLLLULLLDLDLLUUUURRDDDDDRDDLLURRDRUUUDLLUURRRRRRUUULLLLLLDDRRRDDDRRDDRRUURUUDDLDDLLUUUURR
Solution:
##############
#         #**#
# # #####  **#
#       # #* #
# #       @**#
#   #  # ## ##
# #      #   #
#     ## # ###
#            #
##############
inmaps/test030.in
Testing solution...We have searched num gamestates: 19756
passed! Returned:
LLUUULURRRRRURDDDDDDDLDRRRURDDDDRDLLLLLLDLURULLLUUULLLDDDRRDRUUUDLDLLUUURRURRDLLULLDDDDRRRRRRDRRRRRUUUULLLUUUUUUULLLLLDDDDRRULDLUUULURRRRRURDDDDDDDLDRRRURDDDDRDLLLLLLDLURULLLUUULULLDDDDRRRRRURDLDRRRRRDRUUUURULLLDLUUUUUUURULLLLLULDDDDUUURRRRRDDDDDDDRRRDDDDLLLLLLULLLLLUUURURRDDDDRRRDRRRRRUUUULLLUUUUUUULLLLLDDDLDLLURRDRRLUUULURRRRRURDDDDDDDLDRRRURDDDDRDLLLLLLDLURULLLUUUULLDLDDDRRRRRURDLDRRRRRDRUUUURULLLDLUUUUUUURULLLLLULDDDDRDLULLDRURRDLUUUURRRRRDDDDDDDRRRDDDDLLLLLLULLUUUULLDRURDDDLDRRRURDLDRRRRRDRUUUURULLLDLUUUUUUURULLLLLULDDDDRRRDL
Solution:
###############
####  ##  #####
###        ####
###  ####  ####
#### #### #####
#       # #####
#  ***@ # #####
######### #####
#     ##  #  ##
#     ##      #
# ## ####  #  #
# #  #  #### ##
#       ####  #
###  #        #
######  ###  ##
###############
inmaps/test031.in
Testing solution...We have searched num gamestates: 74322
passed! Returned:
RRLLLDLDDRURRRRUUURUULLDRDDLLLLDLDRUURRRRDDLLUDRRUUURRDDDLRUUULLDDRDRUUDLLUUULLUULLLDDRDRDRRLDDRRUULLLULDDLDDRUUDRRUURRUDLLLULULUURRRRDRRDULLLULLLDDRDRDRRRUULLUULLLDDDRRDRDDLLUURRRRDDLDLUUDLLUURRLLDDRRRRUUUURULDDDDDLLUURLDDRRUUUULLUURDLULLLDDRDDDLDRRLUURRRRDDLDLUUDLLUURRLLDDRRRRUUUURULDDDDDLLUURLDDRRUUUUDDLLLULULUURDURRDDRLUULLDLDDRRDRRRDRRDLLLDLUUDLLUURRRLDDRRUULLLULLUURURRDDRRLLUULLDLDDRRDRRRUDLLLLUULUURRRRDRLLULLDDDDDLDRRLUURRRRDDLDLUUDLLUURRDDRRUUUUDDDDLLUURLDDRRUUU
Solution:
##########
#     ####
#  #  **##
#  # ***##
#   ##@**#
##     # #
#  # #   #
#        #
#  #  ####
##########
inmaps/test032.in
Testing solution...We have searched num gamestates: 13877
passed! Returned:
DLRDLRDDLUURUULLLDDRRLLUURRRDDUUUULDRDDDLLLUURRLLDDRRRUUDDLDDRUULLLUURRDDUURRRRDDLLLLRRRRUULLDULLUURRDDLUDLDDRUULLLDRLDR
Solution:
  #####  
  # * #  
### * ###
#       #
#  * *# #
# @* *  #
###* *###
  #   #  
  #####  
inmaps/test033.in
Testing solution...We have searched num gamestates: 926
passed! Returned:
LLLLDLLUUURUURRDDRLUULLDDLDDDRRURRRURUULDDDDDUUUULLDUUULLDDLDDDRRURUUUULLDRURDDRRDDDDRDLUUUUULLULLDLDDDRRURRLLDLLUUURURRDRRDDDDUUUULLDUULLDLDDDRRURUURRUULRDDLLULUURDDURRDDDDDDRDDLLURDRULUUUUUUULLDDRRUULLLDLDLDDDRRURRLLDLLUUURURRDRRDDDDDRDLUUUUUULLDURRUULLLDLDLDDDRRURRLUURRDDDD
Solution:
  ####   
###  ### 
#      ##
#    #  #
#  #    #
# ## #  #
# #     #
#   ## ##
#####*@*#
    # * #
    #*  #
    #####
inmaps/test034.in
Testing solution...We have searched num gamestates: 146
passed! Returned:
LDDDLDRRRULLUUUUURDLDDDDLLLDRRRRLLLLDDRULURRRUUURUDLDDRRRRUUULLLDLLUURDDDULLDDRRRLUUUUURRRDULLLDDRRRURDDDURRDDLLUUULLLLUURDURRDDLLULDDDULLDDRR
Solution:
############
####    ####
###   #  ###
###      ###
##    ##   #
## # ### # #
#   @***   #
#    *** ###
#  #########
#  #########
############
inmaps/test035.in
Testing solution...We have searched num gamestates: 180
passed! Returned:
RUULLDLLDDDDDRRRRRRRULRRULDLDLLLUUUUURRRDRRULLLLDLURULDLUURULLLRRRDDRRDRDLLRUULLDLLLDDRRRUURULDLUURULLRRDDRRUURRDLULDDLDDRRULLDLURULDLUURULDDDRDDDDDRRUUUDDDLLUUUURURRDLLRDDDDLLUUUURULLLULDDLDDRDDRRRUUULLLULDDRDLRUURRRDDDRRRURULDLUUDRRDDLLLLUUUURURRDLLRDDDDLLUUUURULLLULDDLDDRDDRRRUUULLLULDRDL
Solution:
#############
##***  #   ##
#####  #   ##
###      ####
###         #
##  ##      #
##     # ####
#*@ ## #    #
#*  ## #    #
##         ##
#############
inmaps/test036.in
Testing solution...We have searched num gamestates: 63236
passed! Returned:
RRRRRRDRULLLLLLLUURRRDULLLDDRRRRRRUULDRDLLLLRRRRUURRDLULLDDRDRULLUURDDUURRDLDDDLLUURDLULLUULLLDDRRRRRLLLURULDDLLDDRRRUDLLLUURRDRDLRUURRDRRUUULLDRDUURRDLDLLLLLUURDLDRRR
Solution:
###########
# *  #    #
# *  # *  #
# *   @* ##
# *  # * # 
# *  # * # 
########## 
inmaps/test037.in
Testing solution...We have searched num gamestates: 38
passed! Returned:
DULUURDDLDRUUURRDLULDDLDDDDDDRULUURLDDRUDDRRULDLU
Solution:
########
#      #
#      #
##  * ##
 # ** # 
 # ** # 
 # ** # 
 # ** # 
 # @  # 
 #    # 
 ###### 
inmaps/test038.in
Testing solution...We have searched num gamestates: 827
passed! Returned:
LLLLLUDRRRUULUURDRRDDLDLLUUUDDDLLURDRRRURUULLLLLDLDRUURRDDUULLDDDRRLLURLUURRDDUURRRDDLDDRULULLUULLDDRLUURRRUULDDRRRDRDLL
Solution:
   ####   
   #  #   
 ###  ### 
##      ##
#  #**#  #
#   **@  #
##  **  ##
 #####  # 
     #### 
inmaps/test039.in
Testing solution...We have searched num gamestates: 28180
passed! Returned:
RRRRRDRRUULULLULLLLLLDDDDDDRRRRRRURUUUDDRULDDLDLLLLLLUUUUUURDLDDRRRRRRLLLLLDLDDRURDRRRRURURURUULLRRDDLULDLLLLLLLUURRURRDDUULLDLLDDRRRRRRRURRDDLURULDLUDLLLLLLLDDRRDRRUUDDLLULLUURRRRRRRURDRDDLLRRUULDULD
Solution:
########    
#       ### 
#   # #*** #
# *## ##   #
#          #
# *## ##@  #
#   # #*** #
#       ### 
########    
inmaps/test040.in
Testing solution...We have searched num gamestates: 242
passed! Returned:
UUDDDDURLLRURLLRURLLDDRDLDLLUDRRUUUURULULLDURRDDDDDRRDRRULLULLDDRLLLURDRRURUULLDDUURDUUURURRDULLDDDDLDUULUUULLDRRDRRUULLRRRRDLULLLDDRRUDLULLLUR
Solution:
  #####  
###*#*###
# @***  #
#       #
#**   **#
##*   *##
#**   **#
#       #
#  ***  #
###*#*###
  #####  
inmaps/test041.in
Testing solution...We have searched num gamestates: 60340
passed! Returned:
DULDRRDDLLULLLDDRULURDRRURUULLLDURRDRRRDRRULLDLDLLURUULLLDDRRDRURLLLLUURRDULLDDRRLLLDDRULURUURRDDDLRUUULLDDLDDRURRRRURURRDLDLLLLLLDLURRRURLUURDLDDRRRRUULLLULD
Solution:
 ######    
 #    #####
## #@     #
#*******  #
#        ##
#  ####### 
####       
inmaps/test042.in
Testing solution...We have searched num gamestates: 33283
passed! Returned:
LRDDLLUUDLLRRDRULLURDDLLLLUUURURRRDDLDDRRULDLLULDLUUDRUDRDRRULULLRRRUULLLDDUUUURDLDDDRRRUULLRRDDLLLUUUDDDRRURULLRDDLLUUDDRRDDLURULRUULUULRDDLURDRRDDDRRULLLDLDLLURRDRUUUDDLLUUUDDDRRULRURULLRDDLDLU
Solution:
#####    
#** ###  
##* # #  
##*   #  
#**#  ###
#*@     #
#       #
#       #
#########
inmaps/test043.in
Testing solution...We have searched num gamestates: 4849
passed! Returned:
RRURDDULLLLDDRRUDLLUURRDRRLLULDLDRRURRUUULLLUURRDLDLUDRDDURRDDLLDLURUURRULDLURULDDRRDLDLUURULDDDLLURR
Solution:
 #####  
 #*  #  
 #*  ## 
 #*   # 
###   ##
#  @*  #
#     *#
#   **##
####### 
inmaps/test044.in
Testing solution...We have searched num gamestates: 27888
passed! Returned:
RUUDDLLUUDDLLLUULUURUUURDLDRRRLLUURDURRRDLULLDLDDLLDDRDDRRRUURURLDLDDRRUUDDRRRUULLLDDLLUULURDDDLLLUURLDDRRRUUUULRDDDDRRUULRDDLLUURRRRRDDLLLLLLLLUULUURURURDDUUURRDLULDLDLDRLLDDRDDRRRUUUDDDLLLUURRLLDDRRRUU
Solution:
############
##         #
##      ## #
##  **** # #
#   *****  #
# ##*****###
#    @     #
## ## # ## #
##         #
############
inmaps/test045.in
Testing solution...We have searched num gamestates: 113016
passed! Returned:
RRDDDUULRDDLDDLLUUDDRRUURUULULDLLLLDDRULURRURRRUURDLDDRDDLDDLLURDRUDRRURRUULRDDLLLUUULUURDDDDDUUULLULLDRURRRDDDDRRRUULLRRDDLLLLDLLURLUUDDDRDDLUUURRRLLLUDRRRUURRRDDLLDLLULLDDRULURDRRURRRUULDRDLLRUULLULULLLDLDDRLUURURRRURDD
Solution:
############
######  ####
######  ####
###     ####
#   ** @####
#  #**#*   #
#   *#**#  #
####  **   #
####     ###
####  ######
####  ######
############
inmaps/test046.in
Testing solution...We have searched num gamestates: 3677
passed! Returned:
RRRRRRLLLLUUULLDRURDLLULLDRRLLDDRRRRRRRURDLDRRRLLLDLDLLLLUUDDLLUUURRRRRRRDRULURRRLLDRLLLLLLLLLUURRURRDDUULLDLLDDRRRRRRRLLLLLLLDDRDRUUDLLUURRRRRRLLUUURRDRDDLLLLLDDRLUULLUURRRURDDULLLLDDRRRRRRLLLLUDLLUURRRURRRDRDRRDDLULDUUULULLLDLDDRRRRRLLLLLDDRDRULLUUUURURDURRDRDDDRRULDLULLLLLUURRDULLDDRRRRRURDLLLLLLDDRRUDLLUURRRRRDR
Solution:
#########     
#       ##    
#     # *#####
# # # ##  * *#
#        * * #
# # # ## @* *#
#     # *#####
#       ##    
#########     
inmaps/test047.in
Testing solution...We have searched num gamestates: 9540
passed! Returned:
DLUURURURRDLULLLLLLDDRRDRDDDLDLLURRDRUDRRUUDDRRULDLUDLLULLLUUUURRDRDLRRUUUULLLLDDDDDDRRUUDDLLUURLUURRRDRULLLLUURDLDRRLUURRRDURRDLRRDDDLLUUDLLDDUURRDRRDDLLUUDDDLLLUURURLDLDDRU
Solution:
##########
#        #
#  #***  #
#   ** # #
# #*  *# #
#  *  *  #
# # ** # #
#   @#   #
#        #
##########
inmaps/test048.in
Testing solution...We have searched num gamestates: 19726
passed! Returned:
RRRRRUDLLLLDDDRRUUDDLLUUURRRRRDRUUUUUUUURULLLULDRDLULDRDLLRRURURRDDDDDDDDLLLLLLDDRDRUUDLLUURRRRRDRUUUUUUUURULLLULDRRRDDDDDDDDLLLLUUURRDDUULLDDDRRRDRRULLLLRUULRDDRRUUUUUUUULLLLDDLDLLUURDLDRURRUURRDLULDRDLLLDLURRRDLLRRURURURRDDDDDDDDLLLLRRUULULLDRRURDDULLDDRRRDRUUUUUUUURULLLULDRDLULDRDLLDLUDRRURURURRDDDDDDDDLLLLDDLLUURRRRRDRUUUUUUUURULLLULDRDLULDRDLLL
Solution:
    ####   
   ##  ####
####      #
#**#   #  #
#*@   ## ##
#*   ### # 
######## # 
  #    # # 
###    # # 
#  # # # ##
#         #
## # ##   #
 #   ######
 #   #     
 #####     
inmaps/test049.in
Testing solution...We have searched num gamestates: 6510
passed! Returned:
URDDDRRUULDRDLUURULLDLLUDRRRDDDLLURDRURUULLDULLULDDURRRRRDDLURULLLLULDRRRULLDRRDRDDLUURULLL
Solution:
  ######
  #    #
##**** #
#*     #
#*@    #
#*##   #
#*#    #
###    #
  ######
inmaps/test050.in
Testing solution...We have searched num gamestates: 9177
passed! Returned:
LDLUUUDDRRULDDLDDRUULLUDDRDRDDDDLLUURULRRUULDDUUUUULRRRUULDRDLRDDLDDDLLDDDRRUUULUULDDRRDDDLLLLUUURRLLDDDRRUURULUURDDUUURRUULDRDLULDDLDDRRUUULDD
Solution:
########
####*  #
####*  #
##* *  #
###  * #
##*    #
###   ##
### @ ##
# * * ##
# # **##
# # # ##
#     ##
########
inmaps/test051.in
inmaps/test052.in
Testing solution...We have searched num gamestates: 16901
passed! Returned:
LLLDDLLUURUULURRDLDDLDDRUUUULURDDDLUUDDDLLURRDRUUUDDDRRULDLUULURDDRRRRDLLULLDDRURULDLULUURRLLDDRULUR
Solution:
  ######  
  #****#  
  # @**#  
###  #####
#        #
#        #
###   ####
  #####   
inmaps/test053.in
Testing solution...We have searched num gamestates: 368
passed! Returned:
RUUDDLLUUDDRRUULUUUDDDRDDRRRUULLULRDRRDDLLLUULULDRRDDLLLLLUURRRRLLLLDDRRRUDLLLUURRRDDRRRRRUULLULRDRRDDLLLUU
Solution:
###########
#         #
# ###*### #
# #     # #
#  *****  #
###* ** ###
#    *@   #
# ## # ## #
#         #
###########
inmaps/test054.in
Testing solution...We have searched num gamestates: 2292
passed! Returned:
RRUURULRDRRRUUURULLDRDDLDLLURRDRUUULULLDRRRDDDLLLLDDDRLUUURRRRURRDDDDLDLLUULLDLUUDRRRDDLURULRDDRRURUUUULLUULLLLLURRDRRRDDRRDDDDLLDRRUUUUULLLLLLDLLURRRRRDRUURULLLLLRRRRDDRRDDDDLLDLLULLUUULURRRRDRUURULLLRRDDDLLLLDDDRRULDLUUURRRRURRDDDDLLLDLURULLDLURRRDDRRURUUUULLLLLDLLURRRDRRUUURRDDDDDDLLLLLLUUURRURDRULLLDLDDRRRDRRRUUUUULULLULLRDRRRDDLLLLDLLURRDRRRUUDDLLLLDDRRRDRRRUULDRDLLLULLLUUURRRRDLLLLDDRRRDDLURULLDLUUULURRRLDLDDRRRDRRUURUUUUULLLDRDRRDLRDDLDDLLULLLUURRRRUUUDDDLLURDRUURRUULDLDDRU
Solution:
###########
#  * * *  #
# * * * * #
####### @ #
#         #
#       # #
### ####  #
#      #  #
###       #
   ##     #
    #######
inmaps/test055.in
inmaps/test056.in
Testing solution...We have searched num gamestates: 5825
passed! Returned:
LULUURDLDDRRRRRUUUULLDRURDDDUULLLLULDRDLDDRRRUUDDLLLUURURRRURDLLLLDDLUURRRDDDLLLRRRUUURRDUULULULULLDRDDLDDRDDRRUUULLULDDRDLUURRRUUULULDDDLDRRRRURD
Solution:
 #####   
 #   ##  
 #    ## 
 ## #  ##
 #  #   #
##     @#
#*  # #*#
#*  # #*#
#*     *#
#########
inmaps/test057.in
inmaps/test058.in
Testing solution...We have searched num gamestates: 171681
passed! Returned:
LLULULLLLUULURRRRRRLLLLLDDDDLLURDRUUULURRRRRLLLLDDDRRRRDRDDLLLLUULURRLDDRLUULUUURRRRURRDULLDRDRLULLLLLDDDRDDRDRRRUULULLLDLUUULURRRRRURRDULLDLLLLDDDRRRRDRDDLUDLLURUDLLUULUUURRRRURRDRDDUULULLDRDRLULLLLLDDDRDDRRDRRUULULLLDLUUULURRRRRURRDDUULLDRLLLLLDDDRRRRDRDDLLUURULLLDLUUULURRRRRURRDULLDLLLLDDDRRRDDDRULUULLLUUURRRRURRDRDULULLDRRLLLLLLDDDRRRRDRDLLLDLUUDRRUULLDLUUULURRRRRRDRLUURD
Solution:
      ##### 
 ######   ##
 #       @*#
 #  #### **#
### #  ##**#
#       ##*#
#    #   ###
## #       #
 ###     ###
   #######  
inmaps/test059.in
Testing solution...We have searched num gamestates: 108
passed! Returned:
UURUURRRRUURRUURRLLDDLLLLUULLRRDDRRDDLLLLUULUURDDUURRRRLLLLUURD
Solution:
###################
########  ##     ##
#######* @*# #*# ##
#####    *   *   *#
##### #  # #*# ####
##### #  *     *###
##### ##*### ######
##### ##     *#####
##### ## ##########
##### #  ##########
##### # ###########
##### # ###########
##### #############
##### #############
##### #############
#     #############
###################
inmaps/test060.in
Testing solution...We have searched num gamestates: 661
passed! Returned:
UUUURULDDDDDDULLLLDLULURDRUUUUUURULULDRDLULDRRDDDDDDRRRRRRRRDRUUURULDDDLLLLLDDDUUURRRRDRDDDLLLLLLLLDLULURDRRRRUUUULLLLUULLLLDLULURDRUDRRRRRLDDRRRRRRRRRUUULRDDDLLLLUUUUULULDRDLULDRRDDDDLLLLUURRRLLLDDRRRRUUUURULDDDLLLLLLLLUU
Solution:
###################
######  ###########
#####    ##########
#####    #  #######
###*#*# # *   #####
###@### #     #####
#   ### #*#  #*   #
#            ###  #
##  #   ###  ### ##
#####            ##
######  ### ###  ##
########### #### ##
######  *## #### ##
######           ##
#######  ##########
###################
inmaps/test061.in
Testing solution...We have searched num gamestates: 3355
passed! Returned:
DRRUUURULDDLLUULLDDRRDDRRUUUULLLULDRRDDRLDDRRUULLLLDRURRRDDLLULLLDDRULURURRUULLDURRDDDDRRUULLUURDURRDLDDDLLUUUULLDDDRLUUURRRRDDDDLLULLLDDRULUR
Solution:
 ####    
 #  #####
 #      #
 # # *  #
## *** ##
# @* # # 
#  #   # 
#  ##### 
####     
inmaps/test062.in
Testing solution...We have searched num gamestates: 10694
passed! Returned:
RRULUURDDLLRUULDRRURRDDLRDDLRDDLLLLURULRDDRRRUULLLDDRUDRRUUUUUULLDLDDDRLUUURURRDDLLULDRRRDDDDLLUUUDDDRRUUL
Solution:
########
#      #
##   # #
#** *  #
#  * * #
#** *@ #
## * # #
#      #
########
inmaps/test063.in
Testing solution...We have searched num gamestates: 85507
passed! Returned:
LUULURRRLLDDDRRUUDDLLLLLUURLDDRRRUUURUULLDLLUUURRRRDDDLLRDDDDLLLUURRLLDDRRRUULUDRDDRRUULUDRDDRRRUULLLDDLLLLLUURRURUULDURRUULLLLDDDRLUUURRRRDDLDDDLLLDDRRRRRUULLRRDDLLUUUDDDLLLUURR
Solution:
###########
#         #
# ### ### #
# #     # #
#  *****  #
###* ***###
#  @*     #
# ## # ## #
#         #
###########
inmaps/test064.in
Testing solution...We have searched num gamestates: 12144
passed! Returned:
RDDDDDDLLUULUUDDRDDRRUUUUUULLUULLLLLLDDRRRDLDRDRLULUULLUURRRRRRDDRRDDDDDDLLULLDLLURRLLLULUURDDUURUULLUURRRRRRDDRRDDDDDDLLUUUULDLLDULRDLDDRRUULURLLULLDDRLUURRUULLUURRRRRRDDRRDDDDDDLLUULRDDRRUUUUUULLUULLLLLLDDRRDDDRULUULLUURRRRRRDDRRDDDDDDLLUUUULLLRRRDDDDRRUUUUUULLUULLLLLLDDRRRRD
Solution:
###########
#         #
# #####   #
#     #   #
##* *@*## #
#  * *  # #
# *   * # #
#  * *  # #
##* * * # #
 ##   #   #
  #########
inmaps/test065.in
Testing solution...We have searched num gamestates: 7456
passed! Returned:
LUUUUUURRRRDDLULULLDDDDRRUURURULLLRRDDLDDLLUUUURUULLLDDDDDRDRUUDLLUUUUURRRDDLUDRRRDDLDDLLUUUUDDDDRRUUURULDDDDLLULLUURLDDRRUUDDDRRUUULUUDDRDDDLLDDRULUULLUURRRURRDDLURULDLUDRDDDLDLUUUDLLUURRRLDDDRRUUURUL
Solution:
######   
#  **#   
# #**####
# #**@  #
#       #
# # #   #
#   # ###
##    #  
 ##  ##  
  #  #   
  ####   
inmaps/test066.in
Testing solution...We have searched num gamestates: 47
passed! Returned:
LRRDDRRDDDDLLUULLUUDLRDRRDDDDLLULRDDDULRURRUUUULLDLDDRDDDLDDRRRUUUU
Solution:
#########
##*   ###
###*# ###
### #   #
#*  #*# #
##*   # #
#*  # # #
## #*   #
#*  #*###
##*  @###
#*  # ###
##  # ###
## *# ###
##    ###
#########
inmaps/test067.in
inmaps/test068.in
Testing solution...We have searched num gamestates: 1018
passed! Returned:
LUUUUUUUULUULLLLLLLDDRDRRLDDDRRRUUUUDDRRLLDDLLLUUULULUURRRRRRRDDRDRDDLUUDLLLDDDUUURRRURUULLULLLLLLLDDRDRRRURDDDDRULURRLDDLLLLUUULULUURRRRRRRDRRDDDDLURUULRDDLUUDDLLLULLLLULUURDDLDRRRRLLDDDRRRRUURRDDDDDLLLLUUDDRRRRUUUUULLDDLLLLULDDURRRDDRLUURDDLDRRRDRUUUUUUUDLLLDDLLLUUURRURDDDDUUULLLLUUURRDLULDDLDRRRRLLDDDRRRUURRRURUULRDDLUDDLLDDLDDLDRRRDRUURULUUULLLDDLLLUUURRURDDDDDDLDRRRDRUUUUUUU
Solution:
############
#          #
#    #*#** #
#  ##  #** #
#      ##@ #
# # ##     #
#   ##  #  #
#       #  #
#  *#  #*  #
# *#   *#  #
# #        #
#  ###     #
############
inmaps/test069.in
inmaps/test070.in
inmaps/test071.in
Testing solution...We have searched num gamestates: 46715
passed! Returned:
UUDRRRRRUUUUUULLLULLULULLDLLDLDLLURRLURRUULDDLDDDDDDLDRRRDRUUUULURRLDDDDDRRRRUUDDRRRRRUUUURRDLULDDDRDLLLLLDLUUDLLLLULLLUUUUURUDLDDDDDRRRDRRRRRRRRRUUUUUULLLULLULULLDLDLLDLDDDRDLUUUURURRURURRDRDRRDRRRDDDDDDLLLLLLLLLLULUULUUURURRURURRDRDRRDRRRDDDDDDLLLLLLLLLUUUUURRLLDDDDLLUULUUULURDDDDRDDRRDRRRRRRRRRUUUUUULLLULLULULLDLDLURRURRDRDRRDRRRDDDDDDLLLLLLLLLULLUULUUUUURRDLUUURDDLDDLDDDDLDRRRDRUUUULURRLDDDDLLUULUUURUULDDDDDDRDRRDRRRRRRRRRUUUUUULLLULLULULLDLDLLULDDUURURDRRURRDRDRRDRRRDDDDDDLLLLLLLLLLULULLDRRRDRUUUULURDDDDDRRRRRRRRRUUUUUULLLULLULULLDLLLDDLDDDDUUUURUURRDLLULDDRURRURURRDRDRRDRRRDDDDDDLLLLLLLLLLULULLDRRRDRUUDDRRRRRRRRRUUUUUULLLULLULULLDLLLDDLDDDDRDRRUUU
Solution:
##################
###  #############
###  #   #########
##     *  ########
#     ###   ######
#   #######    ###
## # ****##### ###
## # @########   #
##  # ###*####   #
#   # ###*#### ###
# *   ### ####  ##
####            ##
#########  #######
##################
inmaps/test072.in
Testing solution...We have searched num gamestates: 157921
passed! Returned:
URURLDLLULRRURLLLRRDDRUDLDDLDLLULUUURRLDLDDRDRRURUULURULDDRDDRDLLRDDLULRRDRURRUURUULUDRDDLDDLLLUURDLUUURURRDRDDDLDLLDLUUUUUUDDDDRRLLULDURUULULLDLDDRDRRLLULUURURRDRDDRDDLUUUURULLLRDRDDDDDLULURDRUUUURULDLURRRRDRDDDLLLDLUUUULURRR
Solution:
  #########  
 ##*******## 
## *    @* ##
#   #   #   #
#  #*# #*#  #
##  #   #  ##
 #*        # 
  #*      #  
   ##   ##   
     ###     
      #      
      #      
inmaps/test073.in
Testing solution...We have searched num gamestates: 213
passed! Returned:
UURUULDRDDDRRULRUULULLLUURDURRDRD
Solution:
#######
#     #
#  *  #
# * *@#
#* * *#
# * * #
#  *  #
#     #
#######
inmaps/test074.in
Testing solution...We have searched num gamestates: 13343
passed! Returned:
RURLUUURRDDDLLUUULLDDDDDDDLLUUUUUURURDDDUULLDDDDDDRRUURURDLLDDLLUURLUUUURRDDRLUUURRDDDLLUURURDLLDDRDDLUUDDDDLLUURLUUUURRRRURRDDDLLLLDDRUURRRDDUULLLLDDLLUURLDDRRRUURRRDDLLLUURRRUUULLLDLLLDDRRRRRLLLLLUURRRRURRDDDLLLDDLRUULLLDDDDRRUUUDDDLLUURLUUUURRRRURRDDDLLLDLDURURRRUUULLDRURDLLLLLLDDDDRRURULUDRDDLLLUUUURRLLDDRLUURRDDRDDLLLUUUURRURRDLULD
Solution:
#########
##      #
#  @    #
# #*#*#*#
#       #
# #* *#*#
#       #
# #*#*#*#
#   #####
#########
inmaps/test075.in
Testing solution...We have searched num gamestates: 444417
passed! Returned:
RRRRRUDLLLUURRRRRRRRRRRLLLLLLDLULLLLDDRRRURRURRDLLLRRRURRRRRLLLLLLLLLLLLDDRRRUDLLLUURRRRRLLLLLDDRULURRRLLLDDLLUURLDDRRRRRURRRRURRDLRURRRRLLLLLDLLLURRDRRULRRRDLRURRDLULLLLDLLURRRRRRLLLLLLLLLDRRRLLLDLLUURRRLLLDLDLLURURRDDRRURRRURRDLRURRDLULLDLLLURDRRURRRRRDLULLLLDLLURRRRRRLLLLLLLLLLDDRRUDLLUURRRLLLDDLLUURRRLDDRRURURLDLDLLUURRDRRRRURRDLLLLURRDRRURRDLLLLULLDRRRLURRLLLLLLRRRRRRRLLLLLLLDRRRLLLDLLUURRRDRRURRDLLLLULLLDDRRURURRLLDLDLLUURRRDRRRRURRDLLLLURRLLDLLULLLDDRRURURRDRRURLDLLURRLLLLDLDLLUURRRRRLLLLLDDLULURRRRRDRRURLDLLURR
Solution:
###################
#        @********#
#    #            #
#      ############
########           
inmaps/test076.in
Testing solution...We have searched num gamestates: 172945
passed! Returned:
URRUUULURDDDDLLUURLDDRRUUULDLULLDRURRDRDDLLUULURDRULLLDDLDRRRUURRDDDRRULDLUUULLDDRRDRRULDLUUDLLUUURRLDLDDRRUUDDLLDRRURRDDLURULLLDLUUUDDLLDRRRRURRDDLURULLLDLUUDLLUUURRLDLDDRRUU
Solution:
   ###### 
 ###****# 
 #  ****# 
##  @   # 
#  # # ###
#        #
#        #
#######  #
      ####
inmaps/test077.in
inmaps/test078.in
Testing solution...We have searched num gamestates: 210
passed! Returned:
ULULUURDDDLDRURDDUULUURDDDRRURRRRRRUUUULLLDDDLDRRRRURDDLUUUUULLLDDRRLLUURRRDDDDDUUULLDLDRRRUUUULDRDLLDLLDLLLULULUURRRRRRDDDRDLULDDUUURUURDDDLDRRLUURRDDURDLLLLLLLLULULUURRDDDDUUULULDDDD
Solution:
############# 
#           # 
#    # #    # 
#     #     ##
#    ##   #  #
# @          #
# * * # ###**#
# #*###*# #**#
## *  ### ####
 ######       
inmaps/test079.in
Testing solution...We have searched num gamestates: 56
passed! Returned:
UUUUUUUUUUUURRRRRRDRURRDLRDRRDDLLLLDDLDDDDDDRRURULRULULLUURDUUULDDRDLUUURRRRRUULLLRRRDDLLDL
Solution:
##############
########*#####
#          *##
# ##### *  ###
# ######*    #
# ########## #
# #####      #
# ##### *@ ###
# #####   ####
# ####*  *####
# ####* * ####
# ##### *  ###
# ##### *  ###
# ##### #  ###
# #####   ####
##############
inmaps/test080.in
Testing solution...We have searched num gamestates: 881
passed! Returned:
DDDDDDRLDDDDDRRRRDRRULLLLLDLUUUUUUDDDDDRRRRRRDRRULLLDLLULLLUUUUURURRDDRDRDRDULULULUULLDLDDDDDRRRDRRURLDLLULLLUUUUULURRDLDDDDDRRRUULDRDLLDLUUUUUUDDDDDLLLUURDLDRRDRRURRRLLLDLLURRRURRDDLURULRDDRRUL
Solution:
##############
#### #########
#### #########
#### #########
#### #########
#### #########
### * * ######
##*   * ######
#### ##  #####
#### ###  ####
#  # #  #  ###
#  # #*  # ###
#       *@ * #
###   #      #
##############
inmaps/test081.in
Testing solution...We have searched num gamestates: 75487
passed! Returned:
LULLDRURRDDLUDRDDLDLLURRDRUUUDDDRRULRDRUUDLLLDLLULUUDDRDRRUUULULULLDRDDDRDRRURRRURUULDDRDLLLDLUUDRRRUUURUULDDUUUULLDRURDDULLLRURRDDRDDDDLDLLLDLLULUUUURRDRLULLDDDDRDRRULDLLUUUUURRDDRDDLLDLUUDRRRUULUULLDRURDRDDDLLLUUDDRRRUUULLULLDRRLDDDRRRRRRURUULDDRDLLLDLUUDLLLUUURURRLLDLDDDRRRRRRUUURUULDRDDLDDLLLUUUDDDRRRUURUULDDDRDLLLDLUUDRRRUUUUUULLLULLDRRRRURDDDDDDRDLLLLLLDLUUUULURR
Solution:
 ##########
##        #
# #       #
# ######  #
#  @***#  #
#   * *#  #
## #***#  #
#  ## ##  #
#         #
##       ##
 ######### 
inmaps/test082.in
Testing solution...We have searched num gamestates: 339
passed! Returned:
RUDRRLLULURRUULLLLDDDRRDRULLLDDDRRUUDDLLUUURRLLDRRRRLLDDLULURULUUURRRRDRRRDDLURULDDRDDDLLLLLULUULUUURRRRDDRLUULLLLDDDRRURRUURRDLRRDDLURULDDRDDDLLLLLULUURURRRLLLDLDDRDRRRRRUUUUULDLLLLDLDDRURUDLLURURRR
Solution:
##########
#        #
# ###**  #
# #   @* #
#   *##* #
#     ** #
#   *##* #
#        #
##########
inmaps/test083.in
Testing solution...We have searched num gamestates: 33660
passed! Returned:
LLLLLLULDDDDRRUUULURRRDLLDDDRRULDLUUUDDRUDRRRLLLLLUURRURRDLULDRRRRULLDLLLDDRRRRUULURDDDLLUDLLLLRUURRURLDLDDRUUDRU
Solution:
###########
#* ***** *#
#     @   #
##     # ##
#*       *#
#         #
###########
inmaps/test084.in
Testing solution...We have searched num gamestates: 76
passed! Returned:
UULURRRLLDDRLLLDLUUDDDRDLDRRRRRLLLLLDDRDLLRUUURDDLDRRRLULURUULUUURRDDUULLDDDRDRRULLLLLDLUUDRRRURLUURRDDRLULDLU
Solution:
###########
###*#    *#
### #  ####
### *   *##
#*# @  ####
# #     *##
#     * ###
#        *#
###   *####
###   #####
#*     *###
###########
inmaps/test085.in
Testing solution...We have searched num gamestates: 2243
passed! Returned:
ULURRRURDDDDRDDLLURDRUULURRRRRLLLLDDDLLDDLUULURRDRUUDDLLDDLUULURRRRDDDLLLDDDDLDDRUUUUUUUULURRLLDDRRRURUURUULULLLDDDDLDRRRDRUUDRULDLLURR
Solution:
#############
####  #######
#     #######
#  ##  ######
## ##*     *#
#  ##**######
#    @*######
#      ######
#      ######
#      ######
#  ##########
#  ##########
#  ##########
#  ##########
#  ##########
#  ##########
#############
inmaps/test086.in
Testing solution...We have searched num gamestates: 18042
passed! Returned:
LLULLDRRULLLUUUUULURURRDLULDDDDDDUUUUUURRUULDDLDDDDDDLDRRDRRUUUURURRRRDRRUULULLULULLDLLDLULDDDDDDUUUUUURRUULDDRRRURRDLLLLDLURRRRRRDRRDRDDLLULLLUUDDRRRDRRUULULLULLLLLRRRDDDRDRR
Solution:
##############
###  #########
###* #   #####
## *      ####
# *  ## #   ##
#  #### ###  #
## ##*     # #
## ##  #  @* #
## ## ########
#  ## ########
# * * ########
###   * ######
##############
inmaps/test087.in
Testing solution...We have searched num gamestates: 198705
passed! Returned:
RUUULULLDDDDDDRRRRRUUUUUULLDDDDLLRRUUUURRDDDDDDLLLLLUURRRUUUURRDDDDLLUUULLURLLLLLUULLDRLDRRRRRDRRUULDRDLULLLLLUURDLDRRRLDDLUUDDDLLURDRURUULLLDURRRRRRLLLLLLULLDDRLUURRRDRRRRRDRRDDDRRDDLLLLLUUUDDDRRRRRUULLUUULLULLLLLLULLDDRDRDRRUUDDLLURDRURUURRRDRRDDDLLRRUUULLUURDLLLLDDLLLUDRRRUURRRRRDLRDDDRRUUUULRDDDDLLUUULULLLLDDLLLULLUURRRDRRRRRURDLLLLLLUURDLLDULLDDRDRUUDLLUURRRDLDDRRRUURRRRRDDDDRRDDLLLLLUURRRUUUULLLLLLLRRRRRRRDDDDRRUUUULLLLLLLDDLLLULLUURRRDRRRRRLLLDDLUDLLULLUURRRDRRRRLLLLUURDLDRRLLULDRRDDLLUUDLLUURRRURDLDLDDRRURURLDLDLLUURRR
Solution:
  #####        
###   # ####   
#     ###  ####
# #   @****   #
#   #  #*** # #
##     #*## # #
 ##   ##*## # #
  ######      #
       # #### #
       #      #
       ########
inmaps/test088.in
Testing solution...We have searched num gamestates: 60621
passed! Returned:
ULLLULLUUUUURURDDUURRRDDRLUULLLDDRLULLLDLDRURDDDDUUULLDLDDRDRRRRRRRLLLULLUUUUURRURRRDDRRLLUULLLDDRRRLLLULLDDDRRRRUDLLLLUUURRURRRDDLDDLLLLUUURRDDUUURRRDDLDDLLLRUUULLDDDDDUURRRRUURUULLLDLLDLDLDLDDRDRRUUUUUURRURRDDRUULLLDDDDLLDDRRDRRRURRDLULLDDRULURRLLDLLULLDRRRRLLULLUURRUUUURRDDLRUULLDDRRRUULLLLDLDDDRRRRUULLDURRDDLLLRUUULLDDDDDUURRRRUULLULLDLDLDLDDRDRRRRRDRRUDLLULULLUUUUURRURRDRDLLRUULLDDDURRUULLLDLDDDRRUURRRUULLLLDLDDDDDRRDRDRRURRUULDDLDLLURURRDRULLLDRLLLULLUURRUURRDDLLLRUUULLDDDDDUURRRRUULLULLDLDLDLDDRDRRRRRRDRULURDRLLLLULLUURRRRUURUURRDDLLLLRUULLDDDURRDDLLLRUUULLDDDDDUURRRRUULLULLDLDLDLDDRDRRRRULLUURRRRUURRRUURRDDLLRRUULLLLDDLDDLLLLDDRRDRDRRURULDDLLURRLLLULLUURRRRUURUURRDDLLLLRUULLDDDURRDDLLLRUUULLDDDDDUURRRRUULLULLDLDLDLDDRDRRRRRRURRUDLLDDRULUR
Solution:
  #############
  #           #
###    #  # # #
#    #        #
#    # # ######
#  #     #**#  
# ## ##### *#  
#  #   # @* #  
#         **#  
#######   ###  
      #####    
inmaps/test089.in
Testing solution...We have searched num gamestates: 55
passed! Returned:
UUDDLLRRDDUURRRRDRRULLDDLLRRUUUULLDDLLLLLLDLLURRUURRLLDDDDRR
Solution:
     #     #     
    #########    
     #     #     
   ###     ###   
 # # #     # # # 
###### #*# ######
 #     * *     # 
 #   # # # #   # 
 #   *     *   # 
 #   # # # #   # 
 #    @* *     # 
###### #*# ######
 # # #     # # # 
   ###     ###   
     #     #     
    #########    
     #     #     
inmaps/test090.in
inmaps/test091.in
Testing solution...We have searched num gamestates: 6090
passed! Returned:
RRDDRRULDRDDLUDDLLURLDLLURUULDRUUUDDDDDRRUULRRRUULLDUULLDRLUULUURDDD
Solution:
#####    
#   #    
#   #### 
#   #  ##
# *@  * #
 ##* *  #
##  * * #
#  * *  #
# * * * #
##     ##
 ####### 
inmaps/test092.in
Testing solution...We have searched num gamestates: 49
passed! Returned:
UUDDRRLLDDUULLLLULLDRRUURRLLDDDDRRUURRRRRRURRDLLUULLRRDDDDLL
Solution:
###############
#######*#######
###   * *   ###
#   # # # #   #
#   *     *   #
### # # # # ###
###   * *@  ###
#######*#######
###############
inmaps/test093.in
Testing solution...We have searched num gamestates: 790
passed! Returned:
LLLDLDLDLDDDLDRRRRURRRURURURURURRRDDDDDDDDLLLDLDRUURRRRRUUUUULRDDDDDLLLLLLUUURURURURDDDDDUUUURRDDDDDLLLLLDLLUURDLDRURDLLUUURURURURURUULLLDLDLDLDLDLLLDDRULURDRULURDRULURDRULURDRULURDRULURRRRURDDDDDDDDUUUURRDDDDDLLLRUUUUUUUULLLLLDLDLDLDLDLDLLLUURURUDLLUURDRDLULDDDLDRRRRLLLUURURURUDLLUURDRDLULDRDLULDDUUURRUURDLDDDLDLLDDRRRRDRULURDRULURLDLDLLLLUURDLDRRRRURRRULURDRULURDRULURDRULURRRRURDDDDDDDUUURRDDDDDLLLLLDLLUURDDRRURRRRUUUUULLDDDDUUUURRDDDDDLLLLLDLLUURDLDRRLLUUURURURURURUULLLDLDLDLDLDLLLDDRULURDRULURDRULURDRULURDRULURDRULURRRRURDDDDDDDDUUUURRDDDDDLLLLLDLLUURDLDRUUUURURURURUULLLLLDLDLDLDLDLDLLLUURURUUURURRDLDLDLLUURDRDLULDRDLULDDDLDRRRRDRULURDRULURDRULURDRULURDRULURDRULURRRRURDDDDDDDDUUUURRDDDDDLLLLLRRRUUUUULLDLDLDDDUUURURURURUULLLLLDLDLDLDLDLDLLLUUUUURRUURDRDLULDRDLULDRDLULDDDLDRRRRDRULURDRULURDRULURDRULURDRULURDRULURRRRURDDDDDDDDUUUURRDDDDDLLLLLLULD
Solution:
#################  
####     ##  #  #  
###     ##      #  
##     ##    ## ###
#     ##    ##  # #
#    ##    ##     #
#   ##    ##  # # #
#  ##    ##  ## # #
#       ##  ### # #
####*  ##   ### # #
   #**##  @       #
   #######****#####
         ##***#    
          #####    
inmaps/test094.in
Testing solution...We have searched num gamestates: 25172
passed! Returned:
DDDLLURLDLLURDRRULDLLURLLUUURRDLULLLDDRRDRRDRRULRDRRULUULLLULLLLDDDRULUURRRRDRRRDDDLLURLDLLURRLLLULLUURRRRDRRRDDRDLLRUUULLLULLLLDDRRDRRRRDRULLLDRLLULULLDRRRRRRLDRLULLLULLUURRDURRDLULLLDDRULUR
Solution:
#######    
# @*  #### 
#  *     # 
#  *####*##
#       * #
####    * #
   ########
inmaps/test095.in
inmaps/test096.in
Testing solution...We have searched num gamestates: 150055
passed! Returned:
LDLULLUUUUUUUUUURRRRRRDDDDLDDRRURUUURUULDDDDDLDRRULLDLLUURUUUURLDDDDLDDRRURUUUURUULDDDDDURUULULLDDDDLDDRRURRLLDLLUURUUUULLLLLLDDRULURRRRRRRLDDDDLDDRRURUUUURUULDDDDDUUUULLLLLLDLDLDDRUUULURRRRRRRLDDDDLDDRRRUUURUULDDDUUURUULDDULLLLLLDLDDDLDDRUDLDDRULUUUURUURURRRRRRDRDDLDDUURUULDDRUULULLLLLLDLDDLDDDDDDDRULUUUURUUUULURRRRRRRLLLLLDLDDDDLDDRULUURUUURURRRRDDDDLDDRRURUURUULDDUURUULDDULLLLLLDLDDDLDDDDDRULUUUURUUURURRRRDDDDLDDRRURDLLLUURUUUURRDRDDLDDUURUULDDUUULLLLLLDLDDDLDDRUUUUULURRRRRRRLLLLLDLDDDDDLDDRUULUURUUURURRRRDDDDLDDRRURUURUULDDUURUULDDULLLLLLDLDDDLDDDRDDDRRULDLUULUURUDLDDRULUUUURUURURRRRDDDDLDDRRURRDLLDDLLUUUURUUUURRDRDDLDDUURUULDDUUULLLLLLDLDDLDDRUUUULURRRRRRRLLLLLDLDDDDLDDRULUURUUURURRRRDDDDLDDDDRRUUURRDLUUURUULDDDUUURUULDDRDDLDDLDRUUURUULDDRUULULLDDDDLDDDDRRRUULURDDDLUDLLUUUURUUUURRDDDDDUURUULULLDDDDLDDDDRRUUDDLLUURLUURUUUULLLLDLDDDLDDRUUUUULURRRRRRRLDDDDLDDDDRRRUUUUURUULDDDDUUUURUULDDDDD
Solution:
        #### 
        #  # 
#########  # 
#          # 
#   ### #  # 
#  ## # #  # 
#  # ## #  # 
#  # #  #@###
#  # # #****#
#  # #  ****#
#  # # #  ###
#  ###    #  
#    ###  #  
#     #####  
###  ##      
  ####       
inmaps/test097.in
Testing solution...We have searched num gamestates: 90151
passed! Returned:
URRRRRRDDLLLUDRRRUULLLLLLRRRDDRULULLLDDLLURLURRRLLDDRRULDLLURDRRURUUUURULDDDDDLDLLURURLDDRURUUUUDDDRRDDRRUULLLRDLLRRDRURULDLLLUUUDDRDRRULRRDDLLLULUUURUUULLDDRLUURRDLDDDDDRRULDLUUUUURULDDDRUDLDDDLDLLUURRDRUUUUDDDDLDLULURRDRUUURUL
Solution:
   #####   
   #*  #   
   #***#   
   #*@ #   
   #*  #   
##### #####
#         #
#         #
#    #    #
###########
inmaps/test098.in
Testing solution...We have searched num gamestates: 51927
passed! Returned:
RRDRRURUUULLLUDRRRDDDLDLLULLUUURLDDDRRDRRURUUULLDLULLDDDRRRRLLLLUUURRRRRDDDLLLLLUURDLDRRRLLUUUUULURURRDLULDDDDDURRRRDDDRDLUUUULLLLDLDDRRRRRLLLLLUURDLDRRRLLUUUUUURRDLULDDDDURRRRDDDDLRUUUULLLLDLDDRRRRLLLLUURURRRRDDDLDRLULLLLUURDLDRRRRLLLUUURRRRDDDLLLDRULLUUUUURDLDDDDRRRRUUULLLULDDDLDRRRRLLLUUURRDLULDDLDRRR
Solution:
######   
##   #   
#    #   
#    #   
##  #### 
#      # 
#    # # 
#  ### ##
#   @***#
###  ***#
  #######
inmaps/test099.in
Testing solution...We have searched num gamestates: 230
passed! Returned:
RRRRUULLUDLLLLLLDDRRRUDRRRRRUUULUULLLLULDRDRRURRDDLDLLLDDRRUDLLUURRLUULURRRURDLLLLDLULDRRRRURRDULLLDDDLDDLLLUURRUDLLDDRRRRRUULL
Solution:
####     ####
#  #     #  #
# ######### #
###       ###
  #       #  
 ## *   * ## 
 # * # # * # 
 #  *@  *  # 
 # *# # #* # 
 #         # 
 ########### 
  #       #  
  #########  
   #     #   
   #######   
    #   #    
    #####    
     # #     
     ###     
